// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for CreateEpicRequestStatus.
const (
	CreateEpicRequestStatusBacklog    CreateEpicRequestStatus = "backlog"
	CreateEpicRequestStatusDone       CreateEpicRequestStatus = "done"
	CreateEpicRequestStatusInProgress CreateEpicRequestStatus = "in_progress"
)

// Defines values for CreatePromptTemplateRequestType.
const (
	CreatePromptTemplateRequestTypeCustom    CreatePromptTemplateRequestType = "custom"
	CreatePromptTemplateRequestTypeImplement CreatePromptTemplateRequestType = "implement"
	CreatePromptTemplateRequestTypeMerge     CreatePromptTemplateRequestType = "merge"
	CreatePromptTemplateRequestTypeRetry     CreatePromptTemplateRequestType = "retry"
	CreatePromptTemplateRequestTypeReview    CreatePromptTemplateRequestType = "review"
)

// Defines values for CreateStoryRequestScope.
const (
	CreateStoryRequestScopeBackend  CreateStoryRequestScope = "backend"
	CreateStoryRequestScopeFrontend CreateStoryRequestScope = "frontend"
	CreateStoryRequestScopeShared   CreateStoryRequestScope = "shared"
)

// Defines values for EpicStatus.
const (
	EpicStatusBacklog    EpicStatus = "backlog"
	EpicStatusDone       EpicStatus = "done"
	EpicStatusInProgress EpicStatus = "in_progress"
)

// Defines values for PipelineStepActionType.
const (
	PipelineStepActionTypeCustom    PipelineStepActionType = "custom"
	PipelineStepActionTypeImplement PipelineStepActionType = "implement"
	PipelineStepActionTypeMerge     PipelineStepActionType = "merge"
	PipelineStepActionTypeReview    PipelineStepActionType = "review"
	PipelineStepActionTypeTest      PipelineStepActionType = "test"
)

// Defines values for PipelineStepModel.
const (
	ClaudeHaiku43  PipelineStepModel = "claude-haiku-4-3"
	ClaudeOpus46   PipelineStepModel = "claude-opus-4-6"
	ClaudeSonnet45 PipelineStepModel = "claude-sonnet-4-5"
)

// Defines values for PromptTemplateType.
const (
	PromptTemplateTypeCustom    PromptTemplateType = "custom"
	PromptTemplateTypeImplement PromptTemplateType = "implement"
	PromptTemplateTypeMerge     PromptTemplateType = "merge"
	PromptTemplateTypeRetry     PromptTemplateType = "retry"
	PromptTemplateTypeReview    PromptTemplateType = "review"
)

// Defines values for RetryPolicyRetryType.
const (
	Always    RetryPolicyRetryType = "always"
	None      RetryPolicyRetryType = "none"
	OnFailure RetryPolicyRetryType = "on-failure"
)

// Defines values for RunStatus.
const (
	RunStatusCancelled RunStatus = "cancelled"
	RunStatusCompleted RunStatus = "completed"
	RunStatusFailed    RunStatus = "failed"
	RunStatusPending   RunStatus = "pending"
	RunStatusRunning   RunStatus = "running"
)

// Defines values for RunStepStatus.
const (
	RunStepStatusCancelled RunStepStatus = "cancelled"
	RunStepStatusCompleted RunStepStatus = "completed"
	RunStepStatusFailed    RunStepStatus = "failed"
	RunStepStatusPending   RunStepStatus = "pending"
	RunStepStatusRunning   RunStepStatus = "running"
)

// Defines values for RunWithStepsStatus.
const (
	RunWithStepsStatusCancelled RunWithStepsStatus = "cancelled"
	RunWithStepsStatusCompleted RunWithStepsStatus = "completed"
	RunWithStepsStatusFailed    RunWithStepsStatus = "failed"
	RunWithStepsStatusPending   RunWithStepsStatus = "pending"
	RunWithStepsStatusRunning   RunWithStepsStatus = "running"
)

// Defines values for StoryScope.
const (
	StoryScopeBackend  StoryScope = "backend"
	StoryScopeFrontend StoryScope = "frontend"
	StoryScopeShared   StoryScope = "shared"
)

// Defines values for StoryStatus.
const (
	StoryStatusBacklog StoryStatus = "backlog"
	StoryStatusDone    StoryStatus = "done"
	StoryStatusFailed  StoryStatus = "failed"
	StoryStatusRunning StoryStatus = "running"
)

// Defines values for UpdateEpicRequestStatus.
const (
	Backlog    UpdateEpicRequestStatus = "backlog"
	Done       UpdateEpicRequestStatus = "done"
	InProgress UpdateEpicRequestStatus = "in_progress"
)

// Defines values for UpdatePromptTemplateRequestType.
const (
	UpdatePromptTemplateRequestTypeCustom    UpdatePromptTemplateRequestType = "custom"
	UpdatePromptTemplateRequestTypeImplement UpdatePromptTemplateRequestType = "implement"
	UpdatePromptTemplateRequestTypeMerge     UpdatePromptTemplateRequestType = "merge"
	UpdatePromptTemplateRequestTypeRetry     UpdatePromptTemplateRequestType = "retry"
	UpdatePromptTemplateRequestTypeReview    UpdatePromptTemplateRequestType = "review"
)

// Defines values for UpdateStoryRequestScope.
const (
	Backend  UpdateStoryRequestScope = "backend"
	Frontend UpdateStoryRequestScope = "frontend"
	Shared   UpdateStoryRequestScope = "shared"
)

// Defines values for UpdateUserRequestRole.
const (
	UpdateUserRequestRoleAdmin UpdateUserRequestRole = "admin"
	UpdateUserRequestRoleUser  UpdateUserRequestRole = "user"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// CreateEpicRequest defines model for CreateEpicRequest.
type CreateEpicRequest struct {
	Description *string                  `json:"description,omitempty"`
	Name        string                   `json:"name"`
	Status      *CreateEpicRequestStatus `json:"status,omitempty"`
}

// CreateEpicRequestStatus defines model for CreateEpicRequest.Status.
type CreateEpicRequestStatus string

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreatePromptTemplateRequest defines model for CreatePromptTemplateRequest.
type CreatePromptTemplateRequest struct {
	Name            string                          `json:"name"`
	TemplateContent string                          `json:"template_content"`
	Type            CreatePromptTemplateRequestType `json:"type"`
}

// CreatePromptTemplateRequestType defines model for CreatePromptTemplateRequest.Type.
type CreatePromptTemplateRequestType string

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	PipelineConfig struct {
		Steps []struct {
			Action string `json:"action"`
			Name   string `json:"name"`
		} `json:"steps"`
	} `json:"pipeline_config"`
	StoryId openapi_types.UUID `json:"story_id"`
}

// CreateStoryRequest defines model for CreateStoryRequest.
type CreateStoryRequest struct {
	AcceptanceCriteria *string                  `json:"acceptance_criteria,omitempty"`
	DependsOn          *[]string                `json:"depends_on,omitempty"`
	EpicId             *openapi_types.UUID      `json:"epic_id,omitempty"`
	Key                string                   `json:"key"`
	Objective          *string                  `json:"objective,omitempty"`
	Scope              *CreateStoryRequestScope `json:"scope,omitempty"`
	Status             *StoryStatus             `json:"status,omitempty"`
	TargetFiles        *[]string                `json:"target_files,omitempty"`
	Title              string                   `json:"title"`
}

// CreateStoryRequestScope defines model for CreateStoryRequest.Scope.
type CreateStoryRequestScope string

// Epic defines model for Epic.
type Epic struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	ProjectId   openapi_types.UUID `json:"project_id"`
	Status      EpicStatus         `json:"status"`
	StoryCounts StoryCounts        `json:"story_counts"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// EpicStatus defines model for Epic.Status.
type EpicStatus string

// EpicList defines model for EpicList.
type EpicList struct {
	Data       []Epic     `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ImportStoriesRequest defines model for ImportStoriesRequest.
type ImportStoriesRequest struct {
	// Content Raw markdown content with YAML frontmatter story blocks
	Content string `json:"content"`
}

// ImportStoriesResult defines model for ImportStoriesResult.
type ImportStoriesResult struct {
	Errors []ImportStoryError `json:"errors"`

	// Failed Number of stories that failed to import
	Failed int `json:"failed"`

	// Imported Number of newly created stories
	Imported int `json:"imported"`

	// Updated Number of updated stories (key already existed)
	Updated int `json:"updated"`
}

// ImportStoryError defines model for ImportStoryError.
type ImportStoryError struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Key Story key (may be empty if key could not be extracted)
	Key string `json:"key"`

	// Message Human-readable error description
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Page    int `json:"page"`
	PerPage int `json:"per_page"`
	Total   int `json:"total"`
}

// PipelineConfig defines model for PipelineConfig.
type PipelineConfig struct {
	ProjectId openapi_types.UUID `json:"project_id"`
	Steps     []PipelineStep     `json:"steps"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// PipelineStep defines model for PipelineStep.
type PipelineStep struct {
	ActionType  PipelineStepActionType `json:"action_type"`
	AutoApprove bool                   `json:"auto_approve"`
	Id          openapi_types.UUID     `json:"id"`
	Model       PipelineStepModel      `json:"model"`
	Name        string                 `json:"name"`
	RetryPolicy RetryPolicy            `json:"retry_policy"`
}

// PipelineStepActionType defines model for PipelineStep.ActionType.
type PipelineStepActionType string

// PipelineStepModel defines model for PipelineStep.Model.
type PipelineStepModel string

// Project defines model for Project.
type Project struct {
	// CircuitBreakerActive Whether the circuit breaker is currently tripped
	CircuitBreakerActive bool `json:"circuit_breaker_active"`

	// CircuitBreakerCount Number of consecutive pipeline failures
	CircuitBreakerCount int `json:"circuit_breaker_count"`

	// CircuitBreakerMax Threshold for consecutive failures before tripping
	CircuitBreakerMax int                `json:"circuit_breaker_max"`
	CreatedAt         time.Time          `json:"created_at"`
	Description       *string            `json:"description,omitempty"`
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	OwnerId           openapi_types.UUID `json:"owner_id"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Data       []Project  `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// PromptTemplate defines model for PromptTemplate.
type PromptTemplate struct {
	CreatedAt       time.Time          `json:"created_at"`
	Id              openapi_types.UUID `json:"id"`
	Name            string             `json:"name"`
	ProjectId       openapi_types.UUID `json:"project_id"`
	TemplateContent string             `json:"template_content"`
	Type            PromptTemplateType `json:"type"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

// PromptTemplateType defines model for PromptTemplate.Type.
type PromptTemplateType string

// PromptTemplateList defines model for PromptTemplateList.
type PromptTemplateList struct {
	Data       []PromptTemplate `json:"data"`
	Pagination Pagination       `json:"pagination"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// RetryPolicy defines model for RetryPolicy.
type RetryPolicy struct {
	MaxRetries int                  `json:"max_retries"`
	RetryType  RetryPolicyRetryType `json:"retry_type"`
}

// RetryPolicyRetryType defines model for RetryPolicy.RetryType.
type RetryPolicyRetryType string

// Run defines model for Run.
type Run struct {
	CompletedAt            *time.Time              `json:"completed_at,omitempty"`
	CreatedAt              time.Time               `json:"created_at"`
	ErrorMessage           *string                 `json:"error_message,omitempty"`
	Id                     openapi_types.UUID      `json:"id"`
	PipelineConfigSnapshot *map[string]interface{} `json:"pipeline_config_snapshot,omitempty"`
	ProjectId              openapi_types.UUID      `json:"project_id"`
	StartedAt              *time.Time              `json:"started_at,omitempty"`
	Status                 RunStatus               `json:"status"`
	StoryId                openapi_types.UUID      `json:"story_id"`
	UpdatedAt              time.Time               `json:"updated_at"`
}

// RunStatus defines model for Run.Status.
type RunStatus string

// RunList defines model for RunList.
type RunList struct {
	Data       []Run      `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// RunStep defines model for RunStep.
type RunStep struct {
	Action       string             `json:"action"`
	CompletedAt  *time.Time         `json:"completed_at,omitempty"`
	ContainerId  *string            `json:"container_id,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	ErrorMessage *string            `json:"error_message,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	LogTail      *string            `json:"log_tail,omitempty"`
	RunId        openapi_types.UUID `json:"run_id"`
	StartedAt    *time.Time         `json:"started_at,omitempty"`
	Status       RunStepStatus      `json:"status"`
	StepName     string             `json:"step_name"`
	StepOrder    int                `json:"step_order"`
}

// RunStepStatus defines model for RunStep.Status.
type RunStepStatus string

// RunWithSteps defines model for RunWithSteps.
type RunWithSteps struct {
	CompletedAt            *time.Time              `json:"completed_at,omitempty"`
	CreatedAt              time.Time               `json:"created_at"`
	ErrorMessage           *string                 `json:"error_message,omitempty"`
	Id                     openapi_types.UUID      `json:"id"`
	PipelineConfigSnapshot *map[string]interface{} `json:"pipeline_config_snapshot,omitempty"`
	ProjectId              openapi_types.UUID      `json:"project_id"`
	StartedAt              *time.Time              `json:"started_at,omitempty"`
	Status                 RunWithStepsStatus      `json:"status"`
	Steps                  []RunStep               `json:"steps"`
	StoryId                openapi_types.UUID      `json:"story_id"`
	UpdatedAt              time.Time               `json:"updated_at"`
}

// RunWithStepsStatus defines model for RunWithSteps.Status.
type RunWithStepsStatus string

// Story defines model for Story.
type Story struct {
	AcceptanceCriteria *string             `json:"acceptance_criteria,omitempty"`
	CreatedAt          time.Time           `json:"created_at"`
	DependsOn          *[]string           `json:"depends_on,omitempty"`
	EpicId             *openapi_types.UUID `json:"epic_id,omitempty"`
	Id                 openapi_types.UUID  `json:"id"`

	// Key Unique story identifier within project (e.g., S-01)
	Key         string             `json:"key"`
	Objective   *string            `json:"objective,omitempty"`
	ProjectId   openapi_types.UUID `json:"project_id"`
	Scope       *StoryScope        `json:"scope,omitempty"`
	Status      StoryStatus        `json:"status"`
	TargetFiles *[]string          `json:"target_files,omitempty"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// StoryScope defines model for Story.Scope.
type StoryScope string

// StoryCounts defines model for StoryCounts.
type StoryCounts struct {
	Backlog int `json:"backlog"`
	Done    int `json:"done"`
	Failed  int `json:"failed"`
	Running int `json:"running"`
}

// StoryList defines model for StoryList.
type StoryList struct {
	Data       []Story    `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// StoryListOrSingle Returns StoryList for list queries, or single Story for key lookup
type StoryListOrSingle struct {
	union json.RawMessage
}

// StoryStatus defines model for StoryStatus.
type StoryStatus string

// UpdateEpicRequest defines model for UpdateEpicRequest.
type UpdateEpicRequest struct {
	Description *string                  `json:"description,omitempty"`
	Name        *string                  `json:"name,omitempty"`
	Status      *UpdateEpicRequestStatus `json:"status,omitempty"`
}

// UpdateEpicRequestStatus defines model for UpdateEpicRequest.Status.
type UpdateEpicRequestStatus string

// UpdatePipelineConfigRequest defines model for UpdatePipelineConfigRequest.
type UpdatePipelineConfigRequest struct {
	Steps []PipelineStep `json:"steps"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdatePromptTemplateRequest defines model for UpdatePromptTemplateRequest.
type UpdatePromptTemplateRequest struct {
	Name            *string                          `json:"name,omitempty"`
	TemplateContent *string                          `json:"template_content,omitempty"`
	Type            *UpdatePromptTemplateRequestType `json:"type,omitempty"`
}

// UpdatePromptTemplateRequestType defines model for UpdatePromptTemplateRequest.Type.
type UpdatePromptTemplateRequestType string

// UpdateStoryRequest defines model for UpdateStoryRequest.
type UpdateStoryRequest struct {
	AcceptanceCriteria *string                  `json:"acceptance_criteria,omitempty"`
	DependsOn          *[]string                `json:"depends_on,omitempty"`
	EpicId             *openapi_types.UUID      `json:"epic_id,omitempty"`
	Objective          *string                  `json:"objective,omitempty"`
	Scope              *UpdateStoryRequestScope `json:"scope,omitempty"`
	Status             *StoryStatus             `json:"status,omitempty"`
	TargetFiles        *[]string                `json:"target_files,omitempty"`
	Title              *string                  `json:"title,omitempty"`
}

// UpdateStoryRequestScope defines model for UpdateStoryRequest.Scope.
type UpdateStoryRequestScope string

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email *openapi_types.Email   `json:"email,omitempty"`
	Name  *string                `json:"name,omitempty"`
	Role  *UpdateUserRequestRole `json:"role,omitempty"`
}

// UpdateUserRequestRole defines model for UpdateUserRequest.Role.
type UpdateUserRequestRole string

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	Role      UserRole            `json:"role"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Data       []User     `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// EpicIdPath defines model for EpicIdPath.
type EpicIdPath = openapi_types.UUID

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// PageParam defines model for PageParam.
type PageParam = int

// PerPageParam defines model for PerPageParam.
type PerPageParam = int

// ProjectIdPath defines model for ProjectIdPath.
type ProjectIdPath = openapi_types.UUID

// RunIdPath defines model for RunIdPath.
type RunIdPath = openapi_types.UUID

// SortByParam defines model for SortByParam.
type SortByParam = string

// StoryIdPath defines model for StoryIdPath.
type StoryIdPath = openapi_types.UUID

// TemplateIdPath defines model for TemplateIdPath.
type TemplateIdPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`

	// SortBy Field to sort by
	SortBy *SortByParam `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// ListEpicsParams defines parameters for ListEpics.
type ListEpicsParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`

	// SortBy Field to sort by
	SortBy *SortByParam `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// ListRunsByProjectParams defines parameters for ListRunsByProject.
type ListRunsByProjectParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListStoriesParams defines parameters for ListStories.
type ListStoriesParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`

	// Status Comma-separated list of statuses to filter by (e.g., backlog,running)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Key Story key to look up (returns single story)
	Key *string `form:"key,omitempty" json:"key,omitempty"`
}

// ListPromptTemplatesParams defines parameters for ListPromptTemplates.
type ListPromptTemplatesParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListRunsByStoryParams defines parameters for ListRunsByStory.
type ListRunsByStoryParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Page Page number
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Items per page
	PerPage *PerPageParam `form:"per_page,omitempty" json:"per_page,omitempty"`

	// SortBy Field to sort by
	SortBy *SortByParam `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// CreateEpicJSONRequestBody defines body for CreateEpic for application/json ContentType.
type CreateEpicJSONRequestBody = CreateEpicRequest

// UpdateEpicJSONRequestBody defines body for UpdateEpic for application/json ContentType.
type UpdateEpicJSONRequestBody = UpdateEpicRequest

// UpdatePipelineConfigJSONRequestBody defines body for UpdatePipelineConfig for application/json ContentType.
type UpdatePipelineConfigJSONRequestBody = UpdatePipelineConfigRequest

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// CreateStoryJSONRequestBody defines body for CreateStory for application/json ContentType.
type CreateStoryJSONRequestBody = CreateStoryRequest

// ImportStoriesJSONRequestBody defines body for ImportStories for application/json ContentType.
type ImportStoriesJSONRequestBody = ImportStoriesRequest

// UpdateStoryJSONRequestBody defines body for UpdateStory for application/json ContentType.
type UpdateStoryJSONRequestBody = UpdateStoryRequest

// CreatePromptTemplateJSONRequestBody defines body for CreatePromptTemplate for application/json ContentType.
type CreatePromptTemplateJSONRequestBody = CreatePromptTemplateRequest

// UpdatePromptTemplateJSONRequestBody defines body for UpdatePromptTemplate for application/json ContentType.
type UpdatePromptTemplateJSONRequestBody = UpdatePromptTemplateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// AsStoryList returns the union data inside the StoryListOrSingle as a StoryList
func (t StoryListOrSingle) AsStoryList() (StoryList, error) {
	var body StoryList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStoryList overwrites any union data inside the StoryListOrSingle as the provided StoryList
func (t *StoryListOrSingle) FromStoryList(v StoryList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStoryList performs a merge with any union data inside the StoryListOrSingle, using the provided StoryList
func (t *StoryListOrSingle) MergeStoryList(v StoryList) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStory returns the union data inside the StoryListOrSingle as a Story
func (t StoryListOrSingle) AsStory() (Story, error) {
	var body Story
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStory overwrites any union data inside the StoryListOrSingle as the provided Story
func (t *StoryListOrSingle) FromStory(v Story) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStory performs a merge with any union data inside the StoryListOrSingle, using the provided Story
func (t *StoryListOrSingle) MergeStory(v Story) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StoryListOrSingle) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StoryListOrSingle) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Log in an existing user
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Log out the current user
	// (POST /auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// Get the currently authenticated user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// List all projects
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)
	// Create a new project
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete a project
	// (DELETE /projects/{id})
	DeleteProject(w http.ResponseWriter, r *http.Request, id IdPath)
	// Get a project by ID
	// (GET /projects/{id})
	GetProject(w http.ResponseWriter, r *http.Request, id IdPath)
	// Update a project
	// (PUT /projects/{id})
	UpdateProject(w http.ResponseWriter, r *http.Request, id IdPath)
	// Reset the circuit breaker for a project
	// (POST /projects/{id}/circuit-breaker/reset)
	ResetCircuitBreaker(w http.ResponseWriter, r *http.Request, id IdPath)
	// List epics for a project with story counts
	// (GET /projects/{projectId}/epics)
	ListEpics(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListEpicsParams)
	// Create a new epic in a project
	// (POST /projects/{projectId}/epics)
	CreateEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Delete an epic
	// (DELETE /projects/{projectId}/epics/{epicId})
	DeleteEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath)
	// Get an epic by ID
	// (GET /projects/{projectId}/epics/{epicId})
	GetEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath)
	// Update an epic
	// (PUT /projects/{projectId}/epics/{epicId})
	UpdateEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath)
	// Get the pipeline configuration for a project
	// (GET /projects/{projectId}/pipeline)
	GetPipelineConfig(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Update the pipeline configuration for a project
	// (PUT /projects/{projectId}/pipeline)
	UpdatePipelineConfig(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// List runs for a project
	// (GET /projects/{projectId}/runs)
	ListRunsByProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListRunsByProjectParams)
	// Create a new pipeline run for a project
	// (POST /projects/{projectId}/runs)
	CreateRun(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// List stories for a project with optional status filtering
	// (GET /projects/{projectId}/stories)
	ListStories(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListStoriesParams)
	// Create a new story in a project
	// (POST /projects/{projectId}/stories)
	CreateStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Bulk import stories from markdown with YAML frontmatter
	// (POST /projects/{projectId}/stories/import)
	ImportStories(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Delete a story
	// (DELETE /projects/{projectId}/stories/{storyId})
	DeleteStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath)
	// Get a story by ID
	// (GET /projects/{projectId}/stories/{storyId})
	GetStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath)
	// Update a story
	// (PUT /projects/{projectId}/stories/{storyId})
	UpdateStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath)
	// Launch a pipeline run for a single story
	// (POST /projects/{projectId}/stories/{storyId}/runs)
	LaunchRun(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath)
	// List prompt templates for a project
	// (GET /projects/{projectId}/templates)
	ListPromptTemplates(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListPromptTemplatesParams)
	// Create a new prompt template in a project
	// (POST /projects/{projectId}/templates)
	CreatePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath)
	// Delete a prompt template
	// (DELETE /projects/{projectId}/templates/{templateId})
	DeletePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath)
	// Get a prompt template by ID
	// (GET /projects/{projectId}/templates/{templateId})
	GetPromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath)
	// Update a prompt template
	// (PUT /projects/{projectId}/templates/{templateId})
	UpdatePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath)
	// Get a run by ID with its steps
	// (GET /runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId RunIdPath)
	// List runs for a story
	// (GET /stories/{storyId}/runs)
	ListRunsByStory(w http.ResponseWriter, r *http.Request, storyId StoryIdPath, params ListRunsByStoryParams)
	// List all users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Delete a user
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// Get a user by ID
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id IdPath)
	// Update a user
	// (PUT /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id IdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Log in an existing user
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out the current user
// (POST /auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the currently authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all projects
// (GET /projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new project
// (POST /projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a project
// (DELETE /projects/{id})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a project by ID
// (GET /projects/{id})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a project
// (PUT /projects/{id})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset the circuit breaker for a project
// (POST /projects/{id}/circuit-breaker/reset)
func (_ Unimplemented) ResetCircuitBreaker(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List epics for a project with story counts
// (GET /projects/{projectId}/epics)
func (_ Unimplemented) ListEpics(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListEpicsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new epic in a project
// (POST /projects/{projectId}/epics)
func (_ Unimplemented) CreateEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an epic
// (DELETE /projects/{projectId}/epics/{epicId})
func (_ Unimplemented) DeleteEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an epic by ID
// (GET /projects/{projectId}/epics/{epicId})
func (_ Unimplemented) GetEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an epic
// (PUT /projects/{projectId}/epics/{epicId})
func (_ Unimplemented) UpdateEpic(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, epicId EpicIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the pipeline configuration for a project
// (GET /projects/{projectId}/pipeline)
func (_ Unimplemented) GetPipelineConfig(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update the pipeline configuration for a project
// (PUT /projects/{projectId}/pipeline)
func (_ Unimplemented) UpdatePipelineConfig(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List runs for a project
// (GET /projects/{projectId}/runs)
func (_ Unimplemented) ListRunsByProject(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListRunsByProjectParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new pipeline run for a project
// (POST /projects/{projectId}/runs)
func (_ Unimplemented) CreateRun(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List stories for a project with optional status filtering
// (GET /projects/{projectId}/stories)
func (_ Unimplemented) ListStories(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListStoriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new story in a project
// (POST /projects/{projectId}/stories)
func (_ Unimplemented) CreateStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk import stories from markdown with YAML frontmatter
// (POST /projects/{projectId}/stories/import)
func (_ Unimplemented) ImportStories(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a story
// (DELETE /projects/{projectId}/stories/{storyId})
func (_ Unimplemented) DeleteStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a story by ID
// (GET /projects/{projectId}/stories/{storyId})
func (_ Unimplemented) GetStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a story
// (PUT /projects/{projectId}/stories/{storyId})
func (_ Unimplemented) UpdateStory(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Launch a pipeline run for a single story
// (POST /projects/{projectId}/stories/{storyId}/runs)
func (_ Unimplemented) LaunchRun(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, storyId StoryIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List prompt templates for a project
// (GET /projects/{projectId}/templates)
func (_ Unimplemented) ListPromptTemplates(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, params ListPromptTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new prompt template in a project
// (POST /projects/{projectId}/templates)
func (_ Unimplemented) CreatePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a prompt template
// (DELETE /projects/{projectId}/templates/{templateId})
func (_ Unimplemented) DeletePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a prompt template by ID
// (GET /projects/{projectId}/templates/{templateId})
func (_ Unimplemented) GetPromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a prompt template
// (PUT /projects/{projectId}/templates/{templateId})
func (_ Unimplemented) UpdatePromptTemplate(w http.ResponseWriter, r *http.Request, projectId ProjectIdPath, templateId TemplateIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a run by ID with its steps
// (GET /runs/{runId})
func (_ Unimplemented) GetRun(w http.ResponseWriter, r *http.Request, runId RunIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List runs for a story
// (GET /stories/{storyId}/runs)
func (_ Unimplemented) ListRunsByStory(w http.ResponseWriter, r *http.Request, storyId StoryIdPath, params ListRunsByStoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user
// (DELETE /users/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user by ID
// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user
// (PUT /users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetCircuitBreaker operation middleware
func (siw *ServerInterfaceWrapper) ResetCircuitBreaker(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetCircuitBreaker(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEpics operation middleware
func (siw *ServerInterfaceWrapper) ListEpics(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEpicsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEpics(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEpic operation middleware
func (siw *ServerInterfaceWrapper) CreateEpic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEpic(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEpic operation middleware
func (siw *ServerInterfaceWrapper) DeleteEpic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "epicId" -------------
	var epicId EpicIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "epicId", chi.URLParam(r, "epicId"), &epicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "epicId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEpic(w, r, projectId, epicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEpic operation middleware
func (siw *ServerInterfaceWrapper) GetEpic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "epicId" -------------
	var epicId EpicIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "epicId", chi.URLParam(r, "epicId"), &epicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "epicId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEpic(w, r, projectId, epicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEpic operation middleware
func (siw *ServerInterfaceWrapper) UpdateEpic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "epicId" -------------
	var epicId EpicIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "epicId", chi.URLParam(r, "epicId"), &epicId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "epicId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEpic(w, r, projectId, epicId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPipelineConfig operation middleware
func (siw *ServerInterfaceWrapper) GetPipelineConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPipelineConfig(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePipelineConfig operation middleware
func (siw *ServerInterfaceWrapper) UpdatePipelineConfig(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePipelineConfig(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunsByProject operation middleware
func (siw *ServerInterfaceWrapper) ListRunsByProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsByProjectParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunsByProject(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStories operation middleware
func (siw *ServerInterfaceWrapper) ListStories(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStoriesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "key" -------------

	err = runtime.BindQueryParameter("form", true, false, "key", r.URL.Query(), &params.Key)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStories(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateStory operation middleware
func (siw *ServerInterfaceWrapper) CreateStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStory(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportStories operation middleware
func (siw *ServerInterfaceWrapper) ImportStories(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportStories(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStory operation middleware
func (siw *ServerInterfaceWrapper) DeleteStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "storyId" -------------
	var storyId StoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "storyId", chi.URLParam(r, "storyId"), &storyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStory(w, r, projectId, storyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStory operation middleware
func (siw *ServerInterfaceWrapper) GetStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "storyId" -------------
	var storyId StoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "storyId", chi.URLParam(r, "storyId"), &storyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStory(w, r, projectId, storyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateStory operation middleware
func (siw *ServerInterfaceWrapper) UpdateStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "storyId" -------------
	var storyId StoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "storyId", chi.URLParam(r, "storyId"), &storyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateStory(w, r, projectId, storyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LaunchRun operation middleware
func (siw *ServerInterfaceWrapper) LaunchRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "storyId" -------------
	var storyId StoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "storyId", chi.URLParam(r, "storyId"), &storyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LaunchRun(w, r, projectId, storyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPromptTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListPromptTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPromptTemplatesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPromptTemplates(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePromptTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreatePromptTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePromptTemplate(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePromptTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeletePromptTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePromptTemplate(w, r, projectId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPromptTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetPromptTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPromptTemplate(w, r, projectId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePromptTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdatePromptTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId TemplateIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", chi.URLParam(r, "templateId"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "templateId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePromptTemplate(w, r, projectId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId RunIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRunsByStory operation middleware
func (siw *ServerInterfaceWrapper) ListRunsByStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "storyId" -------------
	var storyId StoryIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "storyId", chi.URLParam(r, "storyId"), &storyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "storyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRunsByStoryParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRunsByStory(w, r, storyId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", r.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "per_page", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{id}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{id}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{id}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{id}/circuit-breaker/reset", wrapper.ResetCircuitBreaker)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/epics", wrapper.ListEpics)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/epics", wrapper.CreateEpic)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}/epics/{epicId}", wrapper.DeleteEpic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/epics/{epicId}", wrapper.GetEpic)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{projectId}/epics/{epicId}", wrapper.UpdateEpic)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/pipeline", wrapper.GetPipelineConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{projectId}/pipeline", wrapper.UpdatePipelineConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/runs", wrapper.ListRunsByProject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/runs", wrapper.CreateRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/stories", wrapper.ListStories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/stories", wrapper.CreateStory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/stories/import", wrapper.ImportStories)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}/stories/{storyId}", wrapper.DeleteStory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/stories/{storyId}", wrapper.GetStory)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{projectId}/stories/{storyId}", wrapper.UpdateStory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/stories/{storyId}/runs", wrapper.LaunchRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/templates", wrapper.ListPromptTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/templates", wrapper.CreatePromptTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}/templates/{templateId}", wrapper.DeletePromptTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/templates/{templateId}", wrapper.GetPromptTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{projectId}/templates/{templateId}", wrapper.UpdatePromptTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runs/{runId}", wrapper.GetRun)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stories/{storyId}/runs", wrapper.ListRunsByStory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}", wrapper.UpdateUser)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9aW8bObJ/hej3gDcBJEty7MyMgQU2cTK73pdJDDvGYF/WEOjuksR1N9kh2XH0DP/3",
	"BY++2Yduz2Q+JZZ4FOtiVbGq9Oj5LIoZBSqFd/boxZjjCCRw/de7mPgXwSWWC/VXAMLnJJaEUe9Mf4du",
	"bi7eegOPqA9iNWzgURyBd+aBnuoNPA5fEsIh8M4kT2DgCX8BEVbrzRiPsPTOvCQhaqRcxmqmkJzQuff0",
	"NPCa9r4CwRLuQ8v+ZNO9L/EcLhU26turrxBNojvg6eZfEuDLfPcYz8Er7hfADCeh9M4mAy8ilERJpP9v",
	"9yVUwhy42Rh4y94XEiKBYuDI7uHcHvi0GYTj8cCL8DcLw3jcDRFn/wZfNlHDft1CjDhdYEOaXCW0kSUS",
	"2gIAVxM33Pyacflm2UCWXwiEAZIMCcYluls2EEZ9O9XfOuji+RywhGCKpRsAyfiy6fz6yxYMCDN5Qxx8",
	"gigOsYQWVohiiaQd1gKPzFbaCKQnNVnEjArQGusNDq7gSwJCqr98RiVQ/V8cxyHxsYJz9G+hgH0sbPPf",
	"HGbemfdfo1wbjsy3YvSOc8bNVuXDvsEB4nazp4F3zugsJP4eNs7Un2+3RD/A0fwIBYnZChBEmIQvFFS/",
	"MH5HggDo7sHKtkJDhIOIUIR9H4RAGXmfBt4HJn9hCQ32iCXKJJrpPZ8G3g3FiVwwTv4f9gBDaTf1tZ2h",
	"FjzX0q6u0QLHxpzFwCUx3Fxa7NGDbziKQ0gv3xnjSC0PVFqw0QywTDgIT2v490DnSkqPx0rJV0QnlcTi",
	"sjcCOHpdWrKy0umpvi3SvyeOZYXEMhFlzXaH/fuQzb2BB1TdM58LnxA6jTmbcxAK7IBR8G5duidXEp8N",
	"6PkodqeuFy2EGqn2Rlodr6+R0P9F9sYqn37SF4+/LtGla4Fu9K18ziiWqVJuPG4dwLeGMuhC/R0Blcgs",
	"tTq1Uz0+LQhSvs8/WYIwB0TSfQidI30VocdH/e/0HpZPT0dHR173VvqDx4yFskX1DSL1PcvhK4EHtRZw",
	"bf/4iZAsUjjMoSpO7IF/xyHtvGbKXCW0kRwxiSEkVK82I/P6ACEh1v8hytirf4/9lHMbebHXsew6rlPY",
	"DzDneFmbbuBzTTMkJUE/a6K8pp05qOGnGcva6GnEs7p9YompD1OfEwmcYCfOAoiBBmJqUJrhvIH/UpwM",
	"tIvT76wD7x6WZcm4Ho4nZWk7dekWc2LyFZwQCZ+VRUJpVaAKghnXrKr+KxZYIfm2VVe3XW8azddmqMID",
	"5nOQ0xkJQayGMUlkWNFEuQYK2ZzQ1KupaqF25lHYTVd3cYu6Luv8UTC3SyAdj49fDceT4eT002R89nJ8",
	"Nh7/n8JoSuMASxhKYjRDnZnWv7Jrixnmytf48ccx/HQyHg/h+Oe74ckkOBniHyevhicnr16dnp6cjMfj",
	"cRHSJm7se/PXJtprcVoF7NWr7QCW82NfOyGHIR/pWFYpF58lNsrRyeznZujTwEviYNtMUmFeo/NyxA5S",
	"9WyRUQF/UHYTC/A1cf574rSBsMQl6W01cJUAOQQ6xnNCccrsbStc5iOrCNCQlNZynkTb2LVjgPtjnwVV",
	"Dr9+dzX98PHT9JePNx/eukVXYhKaqyMIiIIEh5eFZY1zWoMsAiGU1qoL1AORC3TxFuE7f3L8suCIdPGE",
	"Bj9fuY6PyniDBRfaLqKYcamYmoBovCoLxlvFicIPKML8PmAPFNlR5lj/fP3re6RvmQhLCdyadXch8+9F",
	"jwOaDXuALLQL4aS76M3A+ZpL66zVmXmGSWicwjIOPuhIH2IzfUQCAskFlsgMR5Ip65bxgjGZxc4Gnvmq",
	"fVUKD+ESWalO93CuZoW9bTE7JAP1h3tYIhxywMESwTciJAQvPGeYr6SUUrjzTTMEDVLktxNv+a5dNMsn",
	"+BX7C0JhqADFdyEgvQeygtBkT7liYOrAP0R4ie4AQRTLJSIz/aHPkjDQQqi++SY59svIyJcviHR5i78n",
	"EaZVIItD+pkq6foDgw0XIt8rc6hRYHWAp6xxEgH8r/bPI59FxdvIDHdd6FiIB8Yr17kAP+Fw+VchJsVV",
	"ssFdh0y3yya4DnhZujsqLlJVn05c4pCFuYsjj8euoZJJXMbXyXGnEJhJgzSan23nPI11Ws4bfLrdW05V",
	"n7H1NrbQXkuIXaqw3eo53oLVUzJ4DPCdxkwJ6gaveNoeJahEB6QSrpWDBAMPJ5JNcRxz9rXMfTMcitxG",
	"uGMsBExdpvxPP22H7hELICye1w9xEsCQxYkYngxfqdOZTwSjFOTwZHiaf7bA5D4Zngxfls9eX6OHC9GK",
	"MB2fmcYsJP6yizmv1NhLM9RpLJfCF4bgKSIqpKls7GQqG6ir31OE+wmR0zsO+B74FGd+ePlK+G0BcgEc",
	"yQUgOwfZOYgI5CecA5XhEklO4tjcn53sUt1cG/9t977PqNLaCkSUBlC0iWJ9y2xLp3qsbhfhb/XNPi04",
	"iAULA+3GFjdM90F3MGMczEkV5Qv7vnTuu1cX3BHd7XS5t6WfO4LE9cDPAwVeuy1OT7cDzZ68Wiuo2Vma",
	"+HrQJGxuzlzNBbZI3oIXnJLrsI5wOei/p7DWrq6vlZ4m9h6O2ubjxkGeMw4av2p6NVlZfAvsvh0pLsrP",
	"YYX5CubKJec7d/TqgvYPTAG9ZbD6m9+6TmNh2Z9WdiEHzY+hRYOxhsAIf5sqcUrxmfmJpSSoQg6U00Ay",
	"ZmRVZCmj+n6jQ2sBKfszfMBLUZbQ0oD2cxfBLW3rPHhCXfEVtWsu8/0UfPnW6DdHRz+mhVhJw7XRqWcr",
	"L35TQXEsFkyuHIotXwh9nhv4qoeuP1HEQANj7PKEUvO/jAjFsJmPqQ9haN7icu7I5zc8XPQ8TVnVb0WT",
	"F15ls9eIVZT3VUK3oLEVmx9YTSe0Lejg5P015ZBRiUlu+z8vQQ3ZfCrthVT38RP6BxI8iKcNyRT2W8YD",
	"4IWvG0PpgZfhprhwaZksGcMtaA08+RuRi+s08IfD8OPMO/vcR5a6M0461nAHDnvmidymyazr52ysIwX7",
	"yPNYLR2kmixIviRgPQgSKIdiRuwrIqFp0MLkeg7Q9XA8eVEMsKQpJSvmkKx6ZX6vKSc7uV+LiStrXrHF",
	"fIWaOKU5EcXzOwNxOp2iOOrUNSp/IW0PJ6bquOMFp4KePIEjV+eBsbDtxo3n34KRYRTSYc2M7Cwf+TWh",
	"8xBcpS8y4VSgbKgOxobqP18SUG7DADGOhJ5uRukR97BEIWP3SawdFuhxVeSYVRdGD9xlev16xRTgbnrn",
	"UnijxWG9tOkb+zhefrBdK1ParqSzuj6Y63ztPOn1c6JrHGTgKj9GNuJpm2+GvVNELYTrZmh3knCyKgnT",
	"8qV1qPjUdsD1UrMLYEWxXJO32gOX6RZZmY4dtY8s7N4I/P3k9v5Bc3S7U3AbKHcjVotnUngY6o+3FdS8",
	"joguNVtRaDgLS4TSNUzKABPA+7KuAL6nF5ltBYZ39cTYGnBeGfflQx7woSPFo3XhNdyrGeyKR7Zgr2pW",
	"O6S5qlQT+AkncnmtVkyjz+yewOvEVR36j98+IcnugSKhvC8sEKZoIWX8kYZLZN4PkFkgLRrN/krLRtX0",
	"nFI4Jv8LS1N5R+iMpbms2CR02El/ZzFcyN8YvxfoE+DIc5Ryap2MXl9eaGtZLgAVZ6W+d4QpnhvfUd2c",
	"iomO/kU/LYhAROhZ1vC2pYdshiRP5CJbVG2gAOTYl0f/UicJiQ9UQAHcXy8+KS7ioXfmKeyIs9GIxUDN",
	"mkeMz0d2khipsbnSLp309eWFN/C+AhfmjOOjydFY31cxUBwT78x7eTQ+eqnpLBeaeiOcyMVIu8WaPZlh",
	"U8Wkmg0uAu/MZCbeGDG09a9vWLDcWjVlKfPxqcyakidQrfk9Ho+3treRqnohp4YJiUQXtM4SpQEWgAPb",
	"J+Ea5PDccGqN6TP+VtyfsXMOTa2i+WngnYwnTYBmJx/Va0utNHpnn28HnkiiCPOlgR0RqmRN5/8SOkep",
	"EsVzobWtEtdbtUbGACyRrRzAEpmxQIkWJ3UUvGfzOQSIJbKAwVBrqzVPWjqbWlcnX5lMq67DmWtpDo5z",
	"/Q3kuVnEfbbd89l54QwoLUjYAp7+BiUchctiGRIEXTjj9pm6mSXSh+wd6oXqW3kv1TDZOcl0pUeKIAjK",
	"LL5jNTHuZopCRwQ95efuKVkngzatklIDYUThoYWB7N0pGqVOGUOX6aBBqQVNQ4QqHzLKW6U0BamKg4ut",
	"VXqML7b8eLrdoToo5qg5WMxaahCYQB+boQyp29Chak0chvmiOR2zj26VaemU/FLJ/Y5E31nWv2f5z7L/",
	"HPSx5qF1A7x1ZXMzOhokWXkspLjWSVkUy9EjCZ6MPgrB5BOW6ftWf57TdzX5tJ1iHNJz0txJyIASrIkU",
	"Nemke1LWiaSMRXNchNsxOGg0ILaPqPE+WXgzm2Mz1CsjJcM7ulsi3TzIrYoSB/ZLoeXNCLB9FeaMe+/Z",
	"u+lB/7Tab28qbDOWMVjtktaavhvZtPKhTStXG0HJ4an1EgIpnCUeQioAftCJ7H8ZD5DJXP+Lrux4gQQz",
	"xaJZSQZPqEA+pugOEJYSolhd63iOCT1Cr4OI0CFTZiDQIGaE2iBB1dYWIM8NHG8MGLvVy+eVM2tsbcOX",
	"U5Nedk/Km1htyC4ac04y6s4Mq3BR1tPuaQQx8dvN23d6xMq2banvXh/79g9hDGc9C3pZwhr5piTdZM74",
	"We+GrRjGZv0Sezh2yxnGMEOXuawbKmzID7e7tLWLD+x7NrRNs4k67fVb+95N7PVU1MpettuKV8ykY3cO",
	"zZQyWrtaGj2aTqw9TPxt8GS3Gin0lO13+Wiyb+4R7POaSX0IqgnoVA5N7sNzIMJ4P6J8cFfDkKfmaBQ0",
	"eLOXcSA67covWVnd74lHDuKO7FhVbHY/pB5Po25pvA9SH6Tt+aPSxmIbFsqufNkypC5bMfW5TFVRwu1b",
	"94HUjfI6YidIzc6HHT40w7tDH9un3s4CIc4UxX3HQ9bkoT+kWnJpme3wbKNG4glt95uvEireLNeN6O3T",
	"f96lqkur6Hr5wxqn23J+dbSqidJ6py5H9yqhz9rPLTTq3bObqyuxHG3LE3oYJ3d9ZVF+eCpEOrtYp1Ex",
	"pE3w2nTDddYo71lH1SqRVBZFeChAzShKrUnyBYEkQzMSSuDKLbGlXrYuYGDLJF40/bhE1i+0MWtg0Nwy",
	"TzJdH4KSGP3AbZFJmsymBjXtakqYmrfcpWKs18v0UpFpb8S8Tsb2rtSYOIgIaW2bwuUINrLY1MBbRrE8",
	"YotXrVClQtOlkk21znNWyqXc/z2rZVvLVOcjIyrfV/zR1qK6A5A5v3Xp8ZHtkNqYPVZq+fpMWdPZSXfP",
	"DourNa6DVc0wxPUAo0Bi4ENDTftshzANsiar+YvJ82TpEoe+ScJ723M3V5mcRXmjYmeD4vU499H+cFKP",
	"+PlW9GqPd7jCz0D1i6AbzfX7DKEbFdRwyzVFsZ4HJcb7upMOn7OT2U+lQHrJIGmOWh2MWruKba1uvuyN",
	"Vf6MpzfF01sUTf9LIotoudOIjG0llDVlWs9oJ9lmE0AsUACcfIXAXGc6+GY2+x9RDcOZ65t+SSBRC4ol",
	"9RF80w1ZGT1CaZuAk/HPiMxMZZJmgLQV/MJUX5lsJQXGAJ2Mx+WxRGTDA0ZBjTgpj2C8BhcR+e8cuJKX",
	"3uOE+osthIU21s9bDeXkrXjaYzqGbimhUgr+KZAFV1gziJKReiSp6K6vEE5KC907axAKJfviuw03Ozpu",
	"9q1JKP745/ai0NWF25L1olgOcwh6VC0Ue4E+55iIu6HE/msgSr1TnXnEpV+A/b7iJRVObYqcOPi0W3eN",
	"HvPfzO1XsLFF1u7WT5WfBu5d8FHC1+/UR62QvUsjtZSOPDOSjQ+oOZ5FJUoJIkdFiuO6aa1MOTx9d1jZ",
	"su79dEgu+9Mhli0lNf21mrq/lBk+etS/tf/UlmS2jvOX//T/rlMtOj05q5gKfvsBdZTyjbReMuAQKVD6",
	"a0oO76g5YNGRgrNejK7kgP+ZfrNJ+k2Ly5sI21+gkYY3esT3WVqftVvqRT6Dy4M8a2Vl+ImlVkpq83eB",
	"1j1Ltm0rjh3WBd6YLiW/S5u90rAiRXKzdb5ldI7305hkcyt6n9Qxd5puflM1tnMCtVjYm9NoV+ZxsSni",
	"M+lppfnje8lkbhT4So+bcge7z7eKKwTwrykvlVH4+vICfZ2gOywAxVg3nTR920Y4JqOvE81Udsfa3PLv",
	"wKcF3yJPrdNNdOo5e5puhU50jpnpNdbUYKN9dqG5jLMYr322qUNx7F0M57cvYY2ormhR5ynKTkpT9mP7",
	"MukzYMuByonxLlCqOfFPt0//CQAA//9mDD+jeo8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
