package action

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/zakari/hopeitworks/backend/internal/domain/model"
	"github.com/zakari/hopeitworks/backend/internal/domain/port"
)

// GitPRAction implements model.Action for creating a pull request.
// It renders the PR title from a configurable template using story context,
// uses the branch_name from RunContext.Metadata as the source branch,
// and stores the resulting PR URL in RunContext.Metadata["pr_url"].
type GitPRAction struct {
	gitProviderFactory port.GitProviderFactory
	storyRepo          port.StoryRepository
	projectRepo        port.ProjectRepository
	logger             *slog.Logger
}

// NewGitPRAction creates a new GitPRAction.
func NewGitPRAction(gitProviderFactory port.GitProviderFactory, storyRepo port.StoryRepository, projectRepo port.ProjectRepository, logger *slog.Logger) *GitPRAction {
	return &GitPRAction{gitProviderFactory: gitProviderFactory, storyRepo: storyRepo, projectRepo: projectRepo, logger: logger}
}

// Name returns the action identifier.
func (a *GitPRAction) Name() string { return "git_pr" }

// Execute creates a pull request using the GitProvider via remote API (no local clone needed).
// It reads configuration from runCtx.Metadata:
//   - title_template: PR title template with {story_key}, {story_title}, {scope}, {branch_name} placeholders
//   - target_branch: base branch for the PR (default: "main")
//   - draft: "true" to create a draft PR
//   - branch_name: source branch (required, typically set by git_branch step)
func (a *GitPRAction) Execute(ctx context.Context, runCtx *model.RunContext) error {
	gitProvider, err := a.gitProviderFactory.ForProjectID(ctx, runCtx.ProjectID)
	if err != nil {
		return fmt.Errorf("resolve git provider: %w", err)
	}

	project, err := a.projectRepo.GetByID(ctx, runCtx.ProjectID)
	if err != nil {
		return fmt.Errorf("fetch project: %w", err)
	}
	if project.RepoURL == nil || *project.RepoURL == "" {
		return fmt.Errorf("git_pr: project has no repo_url configured")
	}

	// Read config from metadata
	titleTemplate := metadataString(runCtx.Metadata, "title_template")
	if titleTemplate == "" {
		titleTemplate = "{story_key}: {story_title}"
	}
	targetBranch := metadataString(runCtx.Metadata, "target_branch")
	if targetBranch == "" {
		targetBranch = "main"
	}
	draft := metadataString(runCtx.Metadata, "draft") == "true"

	branchName := metadataString(runCtx.Metadata, "branch_name")
	if branchName == "" {
		return fmt.Errorf("git_pr: branch_name not found in run context metadata — ensure git_branch step ran first")
	}

	story, err := a.storyRepo.GetByID(ctx, runCtx.StoryID)
	if err != nil {
		return fmt.Errorf("fetch story: %w", err)
	}

	scope := ""
	if story.Scope != nil {
		scope = *story.Scope
	}

	title := renderTemplate(titleTemplate, map[string]string{
		"story_key":   story.Key,
		"story_title": story.Title,
		"scope":       scope,
		"branch_name": branchName,
	})
	if draft {
		title = "[Draft] " + title
	}

	body := buildPRBody(story)

	a.logger.Info("creating pull request",
		"branch", branchName, "target", targetBranch,
		"story_key", story.Key, "draft", draft)

	prURL, err := gitProvider.CreateRemotePR(ctx, *project.RepoURL, title, body, branchName, targetBranch)
	if err != nil {
		return fmt.Errorf("create PR: %w", err)
	}

	runCtx.Metadata["pr_url"] = prURL
	a.logger.Info("pull request created", "pr_url", prURL)
	return nil
}

// buildPRBody constructs a standard PR body from story context.
func buildPRBody(story *model.Story) string {
	var b strings.Builder
	b.WriteString("## " + story.Key + ": " + story.Title + "\n\n")
	if story.Objective != nil && *story.Objective != "" {
		obj := *story.Objective
		if len(obj) > 500 {
			obj = obj[:500] + "…"
		}
		b.WriteString("### Objective\n\n" + obj + "\n\n")
	}
	b.WriteString("---\n> Generated by hopeitworks pipeline")
	return b.String()
}

// metadataString extracts a string value from metadata, returning "" if absent or not a string.
func metadataString(meta map[string]any, key string) string {
	v, ok := meta[key].(string)
	if !ok {
		return ""
	}
	return v
}
