run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - goconst
    - misspell
    - revive
    - bodyclose
    - nilerr

issues:
  exclude-dirs:
    - internal/adapter/postgres/db
    - internal/api/handler/gen_*
  exclude-generated: strict
