// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, name, model, image, template_content, type, scope, provider, project_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider
`

type CreateAgentParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Model           pgtype.Text `json:"model"`
	Image           pgtype.Text `json:"image"`
	TemplateContent string      `json:"template_content"`
	Type            string      `json:"type"`
	Scope           string      `json:"scope"`
	Provider        string      `json:"provider"`
	ProjectID       pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.Image,
		arg.TemplateContent,
		arg.Type,
		arg.Scope,
		arg.Provider,
		arg.ProjectID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.Model,
		&i.Image,
		&i.Provider,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider FROM agents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.Model,
		&i.Image,
		&i.Provider,
	)
	return i, err
}

const listAgentsByProject = `-- name: ListAgentsByProject :many
SELECT id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider FROM agents WHERE project_id = $1 ORDER BY name ASC
`

func (q *Queries) ListAgentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TemplateContent,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.Model,
			&i.Image,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByProjectMerged = `-- name: ListAgentsByProjectMerged :many
SELECT id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider FROM agents
WHERE project_id = $1 OR scope = 'global'
ORDER BY scope DESC, name ASC
`

func (q *Queries) ListAgentsByProjectMerged(ctx context.Context, projectID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProjectMerged, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TemplateContent,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.Model,
			&i.Image,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAgents = `-- name: ListGlobalAgents :many
SELECT id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider FROM agents WHERE scope = 'global' ORDER BY name ASC
`

func (q *Queries) ListGlobalAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listGlobalAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TemplateContent,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.Model,
			&i.Image,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $2, model = $3, image = $4, template_content = $5, provider = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, template_content, type, created_at, updated_at, scope, model, image, provider
`

type UpdateAgentParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Model           pgtype.Text `json:"model"`
	Image           pgtype.Text `json:"image"`
	TemplateContent string      `json:"template_content"`
	Provider        string      `json:"provider"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Model,
		arg.Image,
		arg.TemplateContent,
		arg.Provider,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.Model,
		&i.Image,
		&i.Provider,
	)
	return i, err
}
