// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capabilities.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachCapabilityToAgent = `-- name: AttachCapabilityToAgent :exec
INSERT INTO agent_capabilities (agent_id, capability_id)
VALUES ($1, $2)
ON CONFLICT (agent_id, capability_id) DO NOTHING
`

type AttachCapabilityToAgentParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
}

func (q *Queries) AttachCapabilityToAgent(ctx context.Context, arg AttachCapabilityToAgentParams) error {
	_, err := q.db.Exec(ctx, attachCapabilityToAgent, arg.AgentID, arg.CapabilityID)
	return err
}

const createCapability = `-- name: CreateCapability :one
INSERT INTO capabilities (kind, name, version, scope, project_id, spec)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, name, version, scope, project_id, spec, created_at
`

type CreateCapabilityParams struct {
	Kind      string      `json:"kind"`
	Name      string      `json:"name"`
	Version   int32       `json:"version"`
	Scope     string      `json:"scope"`
	ProjectID pgtype.UUID `json:"project_id"`
	Spec      []byte      `json:"spec"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error) {
	row := q.db.QueryRow(ctx, createCapability,
		arg.Kind,
		arg.Name,
		arg.Version,
		arg.Scope,
		arg.ProjectID,
		arg.Spec,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Scope,
		&i.ProjectID,
		&i.Spec,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCapability = `-- name: DeleteCapability :exec
DELETE FROM capabilities WHERE id = $1
`

func (q *Queries) DeleteCapability(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCapability, id)
	return err
}

const detachCapabilityFromAgent = `-- name: DetachCapabilityFromAgent :exec
DELETE FROM agent_capabilities WHERE agent_id = $1 AND capability_id = $2
`

type DetachCapabilityFromAgentParams struct {
	AgentID      uuid.UUID `json:"agent_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
}

func (q *Queries) DetachCapabilityFromAgent(ctx context.Context, arg DetachCapabilityFromAgentParams) error {
	_, err := q.db.Exec(ctx, detachCapabilityFromAgent, arg.AgentID, arg.CapabilityID)
	return err
}

const getCapability = `-- name: GetCapability :one
SELECT id, kind, name, version, scope, project_id, spec, created_at FROM capabilities WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCapability(ctx context.Context, id uuid.UUID) (Capability, error) {
	row := q.db.QueryRow(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Version,
		&i.Scope,
		&i.ProjectID,
		&i.Spec,
		&i.CreatedAt,
	)
	return i, err
}

const listCapabilitiesByScope = `-- name: ListCapabilitiesByScope :many
SELECT id, kind, name, version, scope, project_id, spec, created_at FROM capabilities
WHERE scope = 'global' OR ($1::uuid IS NOT NULL AND project_id = $1::uuid)
ORDER BY kind, name, version DESC
`

func (q *Queries) ListCapabilitiesByScope(ctx context.Context, dollar_1 uuid.UUID) ([]Capability, error) {
	rows, err := q.db.Query(ctx, listCapabilitiesByScope, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capability{}
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Scope,
			&i.ProjectID,
			&i.Spec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilitiesForAgent = `-- name: ListCapabilitiesForAgent :many
SELECT c.id, c.kind, c.name, c.version, c.scope, c.project_id, c.spec, c.created_at
FROM capabilities c
JOIN agent_capabilities ac ON ac.capability_id = c.id
WHERE ac.agent_id = $1
ORDER BY c.kind, c.name
`

func (q *Queries) ListCapabilitiesForAgent(ctx context.Context, agentID uuid.UUID) ([]Capability, error) {
	rows, err := q.db.Query(ctx, listCapabilitiesForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capability{}
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Version,
			&i.Scope,
			&i.ProjectID,
			&i.Spec,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
