// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost_records.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCostByRunStep = `-- name: GetCostByRunStep :one
SELECT id, run_step_id, project_id, tokens_input, tokens_output, cost_usd, model, created_at FROM cost_records WHERE run_step_id = $1 LIMIT 1
`

func (q *Queries) GetCostByRunStep(ctx context.Context, runStepID uuid.UUID) (CostRecord, error) {
	row := q.db.QueryRow(ctx, getCostByRunStep, runStepID)
	var i CostRecord
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.ProjectID,
		&i.TokensInput,
		&i.TokensOutput,
		&i.CostUsd,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const insertCostRecord = `-- name: InsertCostRecord :one
INSERT INTO cost_records (run_step_id, project_id, tokens_input, tokens_output, cost_usd, model)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_step_id, project_id, tokens_input, tokens_output, cost_usd, model, created_at
`

type InsertCostRecordParams struct {
	RunStepID    uuid.UUID      `json:"run_step_id"`
	ProjectID    uuid.UUID      `json:"project_id"`
	TokensInput  int64          `json:"tokens_input"`
	TokensOutput int64          `json:"tokens_output"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
	Model        string         `json:"model"`
}

func (q *Queries) InsertCostRecord(ctx context.Context, arg InsertCostRecordParams) (CostRecord, error) {
	row := q.db.QueryRow(ctx, insertCostRecord,
		arg.RunStepID,
		arg.ProjectID,
		arg.TokensInput,
		arg.TokensOutput,
		arg.CostUsd,
		arg.Model,
	)
	var i CostRecord
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.ProjectID,
		&i.TokensInput,
		&i.TokensOutput,
		&i.CostUsd,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const sumCostByProject = `-- name: SumCostByProject :one
SELECT COALESCE(SUM(cost_usd), 0)::DECIMAL(10,6) AS total_cost,
       COALESCE(SUM(tokens_input), 0)             AS total_input,
       COALESCE(SUM(tokens_output), 0)            AS total_output
FROM cost_records
WHERE project_id = $1 AND created_at >= $2
`

type SumCostByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CreatedAt time.Time `json:"created_at"`
}

type SumCostByProjectRow struct {
	TotalCost   pgtype.Numeric `json:"total_cost"`
	TotalInput  interface{}    `json:"total_input"`
	TotalOutput interface{}    `json:"total_output"`
}

func (q *Queries) SumCostByProject(ctx context.Context, arg SumCostByProjectParams) (SumCostByProjectRow, error) {
	row := q.db.QueryRow(ctx, sumCostByProject, arg.ProjectID, arg.CreatedAt)
	var i SumCostByProjectRow
	err := row.Scan(&i.TotalCost, &i.TotalInput, &i.TotalOutput)
	return i, err
}

const sumCostByRun = `-- name: SumCostByRun :one
SELECT COALESCE(SUM(cr.cost_usd), 0)::DECIMAL(10,6) AS total_cost
FROM cost_records cr
JOIN run_steps rs ON rs.id = cr.run_step_id
WHERE rs.run_id = $1
`

func (q *Queries) SumCostByRun(ctx context.Context, runID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCostByRun, runID)
	var total_cost pgtype.Numeric
	err := row.Scan(&total_cost)
	return total_cost, err
}
