// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (name, scope, project_id, encrypted_value)
VALUES ($1, $2, $3, $4)
RETURNING id, name, scope, project_id, encrypted_value, created_at, updated_at
`

type CreateCredentialParams struct {
	Name           string      `json:"name"`
	Scope          string      `json:"scope"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EncryptedValue []byte      `json:"encrypted_value"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.Name,
		arg.Scope,
		arg.ProjectID,
		arg.EncryptedValue,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.ProjectID,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, name, scope, project_id, encrypted_value, created_at, updated_at FROM credentials WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCredential(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.ProjectID,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalCredentialByName = `-- name: GetGlobalCredentialByName :one
SELECT id, name, scope, project_id, encrypted_value, created_at, updated_at FROM credentials
WHERE name = $1 AND scope = 'global'
LIMIT 1
`

func (q *Queries) GetGlobalCredentialByName(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRow(ctx, getGlobalCredentialByName, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.ProjectID,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectCredentialByName = `-- name: GetProjectCredentialByName :one
SELECT id, name, scope, project_id, encrypted_value, created_at, updated_at FROM credentials
WHERE name = $1 AND scope = 'project' AND project_id = $2
LIMIT 1
`

type GetProjectCredentialByNameParams struct {
	Name      string      `json:"name"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetProjectCredentialByName(ctx context.Context, arg GetProjectCredentialByNameParams) (Credential, error) {
	row := q.db.QueryRow(ctx, getProjectCredentialByName, arg.Name, arg.ProjectID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.ProjectID,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialsByScope = `-- name: ListCredentialsByScope :many
SELECT id, name, scope, project_id, encrypted_value, created_at, updated_at FROM credentials
WHERE scope = 'global' OR ($1::uuid IS NOT NULL AND project_id = $1::uuid)
ORDER BY scope, name
`

func (q *Queries) ListCredentialsByScope(ctx context.Context, dollar_1 uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByScope, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.ProjectID,
			&i.EncryptedValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
