// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, stacks, services, source, commands)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, stacks, services, source, commands, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Stacks    []string  `json:"stacks"`
	Services  []byte    `json:"services"`
	Source    string    `json:"source"`
	Commands  []byte    `json:"commands"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Stacks,
		arg.Services,
		arg.Source,
		arg.Commands,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Stacks,
		&i.Services,
		&i.Source,
		&i.Commands,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, stacks, services, source, commands, created_at, updated_at FROM environments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Stacks,
		&i.Services,
		&i.Source,
		&i.Commands,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentByProjectID = `-- name: GetEnvironmentByProjectID :one
SELECT id, project_id, stacks, services, source, commands, created_at, updated_at FROM environments WHERE project_id = $1 LIMIT 1
`

func (q *Queries) GetEnvironmentByProjectID(ctx context.Context, projectID uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByProjectID, projectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Stacks,
		&i.Services,
		&i.Source,
		&i.Commands,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET stacks = $2, services = $3, source = $4, commands = $5
WHERE id = $1
RETURNING id, project_id, stacks, services, source, commands, created_at, updated_at
`

type UpdateEnvironmentParams struct {
	ID       uuid.UUID `json:"id"`
	Stacks   []string  `json:"stacks"`
	Services []byte    `json:"services"`
	Source   string    `json:"source"`
	Commands []byte    `json:"commands"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.ID,
		arg.Stacks,
		arg.Services,
		arg.Source,
		arg.Commands,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Stacks,
		&i.Services,
		&i.Source,
		&i.Commands,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
