// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: epic_runs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEpicRun = `-- name: CreateEpicRun :one
INSERT INTO epic_runs (project_id, epic_id, status)
VALUES ($1, $2, $3)
RETURNING id, project_id, epic_id, status, created_at, completed_at
`

type CreateEpicRunParams struct {
	ProjectID uuid.UUID     `json:"project_id"`
	EpicID    uuid.UUID     `json:"epic_id"`
	Status    EpicRunStatus `json:"status"`
}

func (q *Queries) CreateEpicRun(ctx context.Context, arg CreateEpicRunParams) (EpicRun, error) {
	row := q.db.QueryRow(ctx, createEpicRun, arg.ProjectID, arg.EpicID, arg.Status)
	var i EpicRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getEpicRun = `-- name: GetEpicRun :one
SELECT id, project_id, epic_id, status, created_at, completed_at FROM epic_runs WHERE id = $1
`

func (q *Queries) GetEpicRun(ctx context.Context, id uuid.UUID) (EpicRun, error) {
	row := q.db.QueryRow(ctx, getEpicRun, id)
	var i EpicRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertEpicRunStory = `-- name: InsertEpicRunStory :exec
INSERT INTO epic_run_stories (epic_run_id, story_id, run_id, group_index, status)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEpicRunStoryParams struct {
	EpicRunID  uuid.UUID   `json:"epic_run_id"`
	StoryID    uuid.UUID   `json:"story_id"`
	RunID      pgtype.UUID `json:"run_id"`
	GroupIndex int32       `json:"group_index"`
	Status     string      `json:"status"`
}

func (q *Queries) InsertEpicRunStory(ctx context.Context, arg InsertEpicRunStoryParams) error {
	_, err := q.db.Exec(ctx, insertEpicRunStory,
		arg.EpicRunID,
		arg.StoryID,
		arg.RunID,
		arg.GroupIndex,
		arg.Status,
	)
	return err
}

const listEpicRunStories = `-- name: ListEpicRunStories :many
SELECT epic_run_id, story_id, run_id, group_index, status FROM epic_run_stories
WHERE epic_run_id = $1
ORDER BY group_index, story_id
`

func (q *Queries) ListEpicRunStories(ctx context.Context, epicRunID uuid.UUID) ([]EpicRunStory, error) {
	rows, err := q.db.Query(ctx, listEpicRunStories, epicRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EpicRunStory{}
	for rows.Next() {
		var i EpicRunStory
		if err := rows.Scan(
			&i.EpicRunID,
			&i.StoryID,
			&i.RunID,
			&i.GroupIndex,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpicRunStatus = `-- name: UpdateEpicRunStatus :one
UPDATE epic_runs
SET status = $1,
    completed_at = $2
WHERE id = $3
RETURNING id, project_id, epic_id, status, created_at, completed_at
`

type UpdateEpicRunStatusParams struct {
	Status      EpicRunStatus      `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateEpicRunStatus(ctx context.Context, arg UpdateEpicRunStatusParams) (EpicRun, error) {
	row := q.db.QueryRow(ctx, updateEpicRunStatus, arg.Status, arg.CompletedAt, arg.ID)
	var i EpicRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateEpicRunStoryStatus = `-- name: UpdateEpicRunStoryStatus :exec
UPDATE epic_run_stories
SET status = $1,
    run_id = $2
WHERE epic_run_id = $3
  AND story_id = $4
`

type UpdateEpicRunStoryStatusParams struct {
	Status    string      `json:"status"`
	RunID     pgtype.UUID `json:"run_id"`
	EpicRunID uuid.UUID   `json:"epic_run_id"`
	StoryID   uuid.UUID   `json:"story_id"`
}

func (q *Queries) UpdateEpicRunStoryStatus(ctx context.Context, arg UpdateEpicRunStoryStatusParams) error {
	_, err := q.db.Exec(ctx, updateEpicRunStoryStatus,
		arg.Status,
		arg.RunID,
		arg.EpicRunID,
		arg.StoryID,
	)
	return err
}
