// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, project_id, entity_type, entity_id, action, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, entity_type, entity_id, action, payload, created_at
`

type CreateEventParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Action     string    `json:"action"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Payload,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getEventsByEntityID = `-- name: GetEventsByEntityID :many
SELECT id, project_id, entity_type, entity_id, action, payload, created_at FROM events
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at ASC
`

type GetEventsByEntityIDParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetEventsByEntityID(ctx context.Context, arg GetEventsByEntityIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByEntityID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsSince = `-- name: GetEventsSince :many
SELECT e.id, e.project_id, e.entity_type, e.entity_id, e.action, e.payload, e.created_at
FROM events e
WHERE e.project_id = $1
  AND e.created_at > (
      SELECT anchor.created_at FROM events anchor WHERE anchor.id = $2
  )
ORDER BY e.created_at ASC
`

type GetEventsSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetEventsSince(ctx context.Context, arg GetEventsSinceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsSince, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByProject = `-- name: ListEventsByProject :many
SELECT id, project_id, entity_type, entity_id, action, payload, created_at FROM events
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListEventsByProject(ctx context.Context, arg ListEventsByProjectParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
