// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_connections.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGitConnectionByProject = `-- name: DeleteGitConnectionByProject :exec
DELETE FROM git_connections WHERE project_id = $1
`

func (q *Queries) DeleteGitConnectionByProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitConnectionByProject, projectID)
	return err
}

const getGitConnectionByProject = `-- name: GetGitConnectionByProject :one
SELECT id, project_id, provider, kind, encrypted_secret, secret_last4, token_type, scopes, status, account_login, expires_at, last_validated_at, validation_error, created_at, updated_at FROM git_connections WHERE project_id = $1 LIMIT 1
`

func (q *Queries) GetGitConnectionByProject(ctx context.Context, projectID uuid.UUID) (GitConnection, error) {
	row := q.db.QueryRow(ctx, getGitConnectionByProject, projectID)
	var i GitConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Kind,
		&i.EncryptedSecret,
		&i.SecretLast4,
		&i.TokenType,
		&i.Scopes,
		&i.Status,
		&i.AccountLogin,
		&i.ExpiresAt,
		&i.LastValidatedAt,
		&i.ValidationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGitConnectionStatus = `-- name: MarkGitConnectionStatus :exec
UPDATE git_connections
SET status=$2, validation_error=$3, last_validated_at=now(), updated_at=now()
WHERE project_id=$1
`

type MarkGitConnectionStatusParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	Status          string      `json:"status"`
	ValidationError pgtype.Text `json:"validation_error"`
}

func (q *Queries) MarkGitConnectionStatus(ctx context.Context, arg MarkGitConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, markGitConnectionStatus, arg.ProjectID, arg.Status, arg.ValidationError)
	return err
}

const setGitConnectionValidation = `-- name: SetGitConnectionValidation :exec
UPDATE git_connections
SET status=$2, account_login=$3, scopes=$4, expires_at=$5,
    last_validated_at=now(), validation_error=$6, updated_at=now()
WHERE project_id=$1
`

type SetGitConnectionValidationParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Status          string             `json:"status"`
	AccountLogin    pgtype.Text        `json:"account_login"`
	Scopes          []string           `json:"scopes"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ValidationError pgtype.Text        `json:"validation_error"`
}

func (q *Queries) SetGitConnectionValidation(ctx context.Context, arg SetGitConnectionValidationParams) error {
	_, err := q.db.Exec(ctx, setGitConnectionValidation,
		arg.ProjectID,
		arg.Status,
		arg.AccountLogin,
		arg.Scopes,
		arg.ExpiresAt,
		arg.ValidationError,
	)
	return err
}

const upsertGitConnectionPAT = `-- name: UpsertGitConnectionPAT :one
INSERT INTO git_connections
  (project_id, provider, kind, encrypted_secret, secret_last4, token_type, scopes,
   status, account_login, expires_at, last_validated_at, validation_error)
VALUES ($1, $2, 'pat', $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (project_id) DO UPDATE SET
  provider=$2, kind='pat', encrypted_secret=$3, secret_last4=$4, token_type=$5,
  scopes=$6, status=$7, account_login=$8, expires_at=$9, last_validated_at=$10,
  validation_error=$11, updated_at=now()
RETURNING id, project_id, provider, kind, encrypted_secret, secret_last4, token_type, scopes, status, account_login, expires_at, last_validated_at, validation_error, created_at, updated_at
`

type UpsertGitConnectionPATParams struct {
	ProjectID       uuid.UUID          `json:"project_id"`
	Provider        string             `json:"provider"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	SecretLast4     pgtype.Text        `json:"secret_last4"`
	TokenType       pgtype.Text        `json:"token_type"`
	Scopes          []string           `json:"scopes"`
	Status          string             `json:"status"`
	AccountLogin    pgtype.Text        `json:"account_login"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastValidatedAt pgtype.Timestamptz `json:"last_validated_at"`
	ValidationError pgtype.Text        `json:"validation_error"`
}

func (q *Queries) UpsertGitConnectionPAT(ctx context.Context, arg UpsertGitConnectionPATParams) (GitConnection, error) {
	row := q.db.QueryRow(ctx, upsertGitConnectionPAT,
		arg.ProjectID,
		arg.Provider,
		arg.EncryptedSecret,
		arg.SecretLast4,
		arg.TokenType,
		arg.Scopes,
		arg.Status,
		arg.AccountLogin,
		arg.ExpiresAt,
		arg.LastValidatedAt,
		arg.ValidationError,
	)
	var i GitConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Kind,
		&i.EncryptedSecret,
		&i.SecretLast4,
		&i.TokenType,
		&i.Scopes,
		&i.Status,
		&i.AccountLogin,
		&i.ExpiresAt,
		&i.LastValidatedAt,
		&i.ValidationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
