// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hitl_requests.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countHITLRequestsFiltered = `-- name: CountHITLRequestsFiltered :one
SELECT COUNT(*) FROM hitl_requests
WHERE ($1::text = '' OR status = $1::text)
`

func (q *Queries) CountHITLRequestsFiltered(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countHITLRequestsFiltered, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingHITLRequestsByProject = `-- name: CountPendingHITLRequestsByProject :one
SELECT COUNT(*)
FROM hitl_requests hr
JOIN run_steps rs ON rs.id = hr.run_step_id
JOIN runs r ON r.id = rs.run_id
WHERE r.project_id = $1
  AND hr.status = 'pending'
`

func (q *Queries) CountPendingHITLRequestsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingHITLRequestsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHITLRequest = `-- name: CreateHITLRequest :one
INSERT INTO hitl_requests (id, run_step_id, gate_type, diff_content, message, status, halt_reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at, diff_url, message, halt_reason, resolution_action
`

type CreateHITLRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	RunStepID   uuid.UUID   `json:"run_step_id"`
	GateType    string      `json:"gate_type"`
	DiffContent pgtype.Text `json:"diff_content"`
	Message     pgtype.Text `json:"message"`
	Status      string      `json:"status"`
	HaltReason  []byte      `json:"halt_reason"`
}

func (q *Queries) CreateHITLRequest(ctx context.Context, arg CreateHITLRequestParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, createHITLRequest,
		arg.ID,
		arg.RunStepID,
		arg.GateType,
		arg.DiffContent,
		arg.Message,
		arg.Status,
		arg.HaltReason,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.DiffUrl,
		&i.Message,
		&i.HaltReason,
		&i.ResolutionAction,
	)
	return i, err
}

const getHITLRequest = `-- name: GetHITLRequest :one
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at, diff_url, message, halt_reason, resolution_action FROM hitl_requests WHERE id = $1
`

func (q *Queries) GetHITLRequest(ctx context.Context, id uuid.UUID) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequest, id)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.DiffUrl,
		&i.Message,
		&i.HaltReason,
		&i.ResolutionAction,
	)
	return i, err
}

const getHITLRequestByRunStepID = `-- name: GetHITLRequestByRunStepID :one
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at, diff_url, message, halt_reason, resolution_action FROM hitl_requests WHERE run_step_id = $1 LIMIT 1
`

func (q *Queries) GetHITLRequestByRunStepID(ctx context.Context, runStepID uuid.UUID) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequestByRunStepID, runStepID)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.DiffUrl,
		&i.Message,
		&i.HaltReason,
		&i.ResolutionAction,
	)
	return i, err
}

const listHITLRequestsFiltered = `-- name: ListHITLRequestsFiltered :many
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at, diff_url, message, halt_reason, resolution_action FROM hitl_requests
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListHITLRequestsFilteredParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListHITLRequestsFiltered(ctx context.Context, arg ListHITLRequestsFilteredParams) ([]HitlRequest, error) {
	rows, err := q.db.Query(ctx, listHITLRequestsFiltered, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlRequest{}
	for rows.Next() {
		var i HitlRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunStepID,
			&i.GateType,
			&i.DiffContent,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.DiffUrl,
			&i.Message,
			&i.HaltReason,
			&i.ResolutionAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHITLRequestsByProject = `-- name: ListPendingHITLRequestsByProject :many
SELECT
    hr.id,
    rs.run_id,
    rs.id AS step_id,
    s.key AS story_key,
    hr.diff_url,
    hr.created_at
FROM hitl_requests hr
JOIN run_steps rs ON rs.id = hr.run_step_id
JOIN runs r ON r.id = rs.run_id
JOIN stories s ON s.id = r.story_id
WHERE r.project_id = $1
  AND hr.status = 'pending'
ORDER BY hr.created_at DESC
`

type ListPendingHITLRequestsByProjectRow struct {
	ID        uuid.UUID   `json:"id"`
	RunID     uuid.UUID   `json:"run_id"`
	StepID    uuid.UUID   `json:"step_id"`
	StoryKey  string      `json:"story_key"`
	DiffUrl   pgtype.Text `json:"diff_url"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) ListPendingHITLRequestsByProject(ctx context.Context, projectID uuid.UUID) ([]ListPendingHITLRequestsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPendingHITLRequestsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingHITLRequestsByProjectRow{}
	for rows.Next() {
		var i ListPendingHITLRequestsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.StoryKey,
			&i.DiffUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeHalts = `-- name: ListProbeHalts :many
SELECT
    hr.id,
    hr.run_step_id,
    hr.gate_type,
    hr.status,
    hr.halt_reason,
    hr.created_at,
    rs.run_id,
    rs.step_name,
    rs.stage_name,
    r.project_id,
    s.key   AS story_key,
    s.title AS story_title
FROM hitl_requests hr
JOIN run_steps rs ON rs.id = hr.run_step_id
JOIN runs r ON r.id = rs.run_id
JOIN stories s ON s.id = r.story_id
WHERE hr.gate_type = 'probe_halt'
  AND hr.status = 'pending'
  AND ($1::uuid IS NULL OR r.project_id = $1::uuid)
ORDER BY hr.created_at DESC
`

type ListProbeHaltsRow struct {
	ID         uuid.UUID   `json:"id"`
	RunStepID  uuid.UUID   `json:"run_step_id"`
	GateType   string      `json:"gate_type"`
	Status     string      `json:"status"`
	HaltReason []byte      `json:"halt_reason"`
	CreatedAt  time.Time   `json:"created_at"`
	RunID      uuid.UUID   `json:"run_id"`
	StepName   string      `json:"step_name"`
	StageName  pgtype.Text `json:"stage_name"`
	ProjectID  uuid.UUID   `json:"project_id"`
	StoryKey   string      `json:"story_key"`
	StoryTitle string      `json:"story_title"`
}

// Pending probe_halt gates across the platform (batch triage inbox). Enriched
// with story/run context and the structured halt_reason so the UI can group by
// reason and suggest a remedy. Ordered newest-first; project filter optional
// (pass the nil UUID to list all projects).
func (q *Queries) ListProbeHalts(ctx context.Context, projectID pgtype.UUID) ([]ListProbeHaltsRow, error) {
	rows, err := q.db.Query(ctx, listProbeHalts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProbeHaltsRow{}
	for rows.Next() {
		var i ListProbeHaltsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunStepID,
			&i.GateType,
			&i.Status,
			&i.HaltReason,
			&i.CreatedAt,
			&i.RunID,
			&i.StepName,
			&i.StageName,
			&i.ProjectID,
			&i.StoryKey,
			&i.StoryTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHITLRequestStatus = `-- name: UpdateHITLRequestStatus :one
UPDATE hitl_requests
SET status = $2,
    resolved_at = $3,
    resolved_by = $4,
    rejection_reason = $5,
    resolution_action = COALESCE($6, resolution_action)
WHERE id = $1
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at, diff_url, message, halt_reason, resolution_action
`

type UpdateHITLRequestStatusParams struct {
	ID               uuid.UUID          `json:"id"`
	Status           string             `json:"status"`
	ResolvedAt       pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy       pgtype.UUID        `json:"resolved_by"`
	RejectionReason  pgtype.Text        `json:"rejection_reason"`
	ResolutionAction pgtype.Text        `json:"resolution_action"`
}

func (q *Queries) UpdateHITLRequestStatus(ctx context.Context, arg UpdateHITLRequestStatusParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, updateHITLRequestStatus,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.RejectionReason,
		arg.ResolutionAction,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.DiffUrl,
		&i.Message,
		&i.HaltReason,
		&i.ResolutionAction,
	)
	return i, err
}
