// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hitl_requests.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingHITLRequestsByProject = `-- name: CountPendingHITLRequestsByProject :one
SELECT COUNT(*)
FROM hitl_requests hr
JOIN run_steps rs ON rs.id = hr.run_step_id
JOIN runs r ON r.id = rs.run_id
WHERE r.project_id = $1
  AND hr.status = 'pending'
`

func (q *Queries) CountPendingHITLRequestsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingHITLRequestsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHITLRequest = `-- name: CreateHITLRequest :one
INSERT INTO hitl_requests (id, run_step_id, gate_type, diff_content, status, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at
`

type CreateHITLRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	RunStepID   uuid.UUID   `json:"run_step_id"`
	GateType    string      `json:"gate_type"`
	DiffContent pgtype.Text `json:"diff_content"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateHITLRequest(ctx context.Context, arg CreateHITLRequestParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, createHITLRequest,
		arg.ID,
		arg.RunStepID,
		arg.GateType,
		arg.DiffContent,
		arg.Status,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getHITLRequest = `-- name: GetHITLRequest :one
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at FROM hitl_requests WHERE id = $1
`

func (q *Queries) GetHITLRequest(ctx context.Context, id uuid.UUID) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequest, id)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getHITLRequestByRunStepID = `-- name: GetHITLRequestByRunStepID :one
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at FROM hitl_requests WHERE run_step_id = $1 LIMIT 1
`

func (q *Queries) GetHITLRequestByRunStepID(ctx context.Context, runStepID uuid.UUID) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequestByRunStepID, runStepID)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingHITLRequestsByProject = `-- name: ListPendingHITLRequestsByProject :many
SELECT
    hr.id,
    rs.run_id,
    rs.id AS step_id,
    s.key AS story_key,
    hr.diff_content,
    hr.created_at
FROM hitl_requests hr
JOIN run_steps rs ON rs.id = hr.run_step_id
JOIN runs r ON r.id = rs.run_id
JOIN stories s ON s.id = r.story_id
WHERE r.project_id = $1
  AND hr.status = 'pending'
ORDER BY hr.created_at DESC
`

type ListPendingHITLRequestsByProjectRow struct {
	ID          uuid.UUID   `json:"id"`
	RunID       uuid.UUID   `json:"run_id"`
	StepID      uuid.UUID   `json:"step_id"`
	StoryKey    string      `json:"story_key"`
	DiffContent pgtype.Text `json:"diff_content"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) ListPendingHITLRequestsByProject(ctx context.Context, projectID uuid.UUID) ([]ListPendingHITLRequestsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPendingHITLRequestsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingHITLRequestsByProjectRow{}
	for rows.Next() {
		var i ListPendingHITLRequestsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepID,
			&i.StoryKey,
			&i.DiffContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHITLRequestStatus = `-- name: UpdateHITLRequestStatus :one
UPDATE hitl_requests
SET status = $2, resolved_at = $3, resolved_by = $4, rejection_reason = $5
WHERE id = $1
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at
`

type UpdateHITLRequestStatusParams struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy      pgtype.UUID        `json:"resolved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
}

func (q *Queries) UpdateHITLRequestStatus(ctx context.Context, arg UpdateHITLRequestStatusParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, updateHITLRequestStatus,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.RejectionReason,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
