// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hitl_requests.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHITLRequest = `-- name: CreateHITLRequest :one
INSERT INTO hitl_requests (id, run_step_id, gate_type, diff_content, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at
`

type CreateHITLRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	RunStepID   uuid.UUID   `json:"run_step_id"`
	GateType    string      `json:"gate_type"`
	DiffContent pgtype.Text `json:"diff_content"`
	Status      string      `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
}

func (q *Queries) CreateHITLRequest(ctx context.Context, arg CreateHITLRequestParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, createHITLRequest,
		arg.ID,
		arg.RunStepID,
		arg.GateType,
		arg.DiffContent,
		arg.Status,
		arg.CreatedAt,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getHITLRequestByRunStepID = `-- name: GetHITLRequestByRunStepID :one
SELECT id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at FROM hitl_requests WHERE run_step_id = $1 LIMIT 1
`

func (q *Queries) GetHITLRequestByRunStepID(ctx context.Context, runStepID uuid.UUID) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequestByRunStepID, runStepID)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateHITLRequestStatus = `-- name: UpdateHITLRequestStatus :one
UPDATE hitl_requests
SET status = $2, resolved_at = $3, resolved_by = $4, rejection_reason = $5
WHERE id = $1
RETURNING id, run_step_id, gate_type, diff_content, status, resolved_at, resolved_by, rejection_reason, created_at
`

type UpdateHITLRequestStatusParams struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy      pgtype.UUID        `json:"resolved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
}

func (q *Queries) UpdateHITLRequestStatus(ctx context.Context, arg UpdateHITLRequestStatusParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, updateHITLRequestStatus,
		arg.ID,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.RejectionReason,
	)
	var i HitlRequest
	err := row.Scan(
		&i.ID,
		&i.RunStepID,
		&i.GateType,
		&i.DiffContent,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
