// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EpicRunStatus string

const (
	EpicRunStatusPending   EpicRunStatus = "pending"
	EpicRunStatusRunning   EpicRunStatus = "running"
	EpicRunStatusCompleted EpicRunStatus = "completed"
	EpicRunStatusFailed    EpicRunStatus = "failed"
	EpicRunStatusPaused    EpicRunStatus = "paused"
)

func (e *EpicRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EpicRunStatus(s)
	case string:
		*e = EpicRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EpicRunStatus: %T", src)
	}
	return nil
}

type NullEpicRunStatus struct {
	EpicRunStatus EpicRunStatus `json:"epic_run_status"`
	Valid         bool          `json:"valid"` // Valid is true if EpicRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEpicRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EpicRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EpicRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEpicRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EpicRunStatus), nil
}

type Agent struct {
	ID              uuid.UUID   `json:"id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	Name            string      `json:"name"`
	TemplateContent string      `json:"template_content"`
	Type            string      `json:"type"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	Scope           string      `json:"scope"`
	Model           pgtype.Text `json:"model"`
	Image           pgtype.Text `json:"image"`
	Provider        string      `json:"provider"`
	RuntimeKind     string      `json:"runtime_kind"`
}

type AgentCapability struct {
	AgentID      uuid.UUID `json:"agent_id"`
	CapabilityID uuid.UUID `json:"capability_id"`
}

type Capability struct {
	ID        uuid.UUID   `json:"id"`
	Kind      string      `json:"kind"`
	Name      string      `json:"name"`
	Version   int32       `json:"version"`
	Scope     string      `json:"scope"`
	ProjectID pgtype.UUID `json:"project_id"`
	Spec      []byte      `json:"spec"`
	CreatedAt time.Time   `json:"created_at"`
}

type CostRecord struct {
	ID           uuid.UUID      `json:"id"`
	RunStepID    uuid.UUID      `json:"run_step_id"`
	ProjectID    uuid.UUID      `json:"project_id"`
	TokensInput  int64          `json:"tokens_input"`
	TokensOutput int64          `json:"tokens_output"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
	Model        string         `json:"model"`
	CreatedAt    time.Time      `json:"created_at"`
	AgentID      pgtype.UUID    `json:"agent_id"`
}

type Credential struct {
	ID             uuid.UUID   `json:"id"`
	Name           string      `json:"name"`
	Scope          string      `json:"scope"`
	ProjectID      pgtype.UUID `json:"project_id"`
	EncryptedValue []byte      `json:"encrypted_value"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Epic struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type EpicRun struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	EpicID      uuid.UUID          `json:"epic_id"`
	Status      EpicRunStatus      `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type EpicRunStory struct {
	EpicRunID  uuid.UUID   `json:"epic_run_id"`
	StoryID    uuid.UUID   `json:"story_id"`
	RunID      pgtype.UUID `json:"run_id"`
	GroupIndex int32       `json:"group_index"`
	Status     string      `json:"status"`
}

type Event struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Action     string    `json:"action"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"created_at"`
}

type HitlRequest struct {
	ID              uuid.UUID          `json:"id"`
	RunStepID       uuid.UUID          `json:"run_step_id"`
	GateType        string             `json:"gate_type"`
	DiffContent     pgtype.Text        `json:"diff_content"`
	Status          string             `json:"status"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy      pgtype.UUID        `json:"resolved_by"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	CreatedAt       time.Time          `json:"created_at"`
	DiffUrl         pgtype.Text        `json:"diff_url"`
	Message         pgtype.Text        `json:"message"`
}

type NotificationConfig struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ChannelType  string    `json:"channel_type"`
	Config       []byte    `json:"config"`
	EventsFilter []byte    `json:"events_filter"`
	Enabled      bool      `json:"enabled"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PipelineConfig struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	ConfigYaml string    `json:"config_yaml"`
	Version    int32     `json:"version"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Project struct {
	ID                   uuid.UUID      `json:"id"`
	Name                 string         `json:"name"`
	Description          pgtype.Text    `json:"description"`
	OwnerID              pgtype.UUID    `json:"owner_id"`
	RepoUrl              pgtype.Text    `json:"repo_url"`
	GitProvider          string         `json:"git_provider"`
	GitTokenEnv          pgtype.Text    `json:"git_token_env"`
	AgentRuntime         string         `json:"agent_runtime"`
	DefaultModel         pgtype.Text    `json:"default_model"`
	MaxBudget            pgtype.Numeric `json:"max_budget"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CircuitBreakerCount  int32          `json:"circuit_breaker_count"`
	CircuitBreakerActive bool           `json:"circuit_breaker_active"`
	CircuitBreakerMax    int32          `json:"circuit_breaker_max"`
}

type ProjectUser struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type RevokedToken struct {
	Jti       string    `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Run struct {
	ID                     uuid.UUID          `json:"id"`
	ProjectID              uuid.UUID          `json:"project_id"`
	StoryID                uuid.UUID          `json:"story_id"`
	Status                 string             `json:"status"`
	PipelineConfigSnapshot []byte             `json:"pipeline_config_snapshot"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage           pgtype.Text        `json:"error_message"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	Metadata               []byte             `json:"metadata"`
}

type RunStep struct {
	ID           uuid.UUID          `json:"id"`
	RunID        uuid.UUID          `json:"run_id"`
	StepName     string             `json:"step_name"`
	StepOrder    int32              `json:"step_order"`
	Action       string             `json:"action"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ContainerID  pgtype.Text        `json:"container_id"`
	LogTail      pgtype.Text        `json:"log_tail"`
	CreatedAt    time.Time          `json:"created_at"`
	RetryCount   int32              `json:"retry_count"`
	RetryType    pgtype.Text        `json:"retry_type"`
	ParentStepID pgtype.UUID        `json:"parent_step_id"`
}

type Story struct {
	ID                 uuid.UUID   `json:"id"`
	ProjectID          uuid.UUID   `json:"project_id"`
	EpicID             pgtype.UUID `json:"epic_id"`
	Key                string      `json:"key"`
	Title              string      `json:"title"`
	Objective          pgtype.Text `json:"objective"`
	TargetFiles        []byte      `json:"target_files"`
	DependsOn          []byte      `json:"depends_on"`
	Scope              pgtype.Text `json:"scope"`
	Status             string      `json:"status"`
	AcceptanceCriteria pgtype.Text `json:"acceptance_criteria"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UserApiKey struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	KeyName      string    `json:"key_name"`
	EncryptedKey []byte    `json:"encrypted_key"`
	KeyHint      string    `json:"key_hint"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
