// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Epic struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	OwnerID      pgtype.UUID    `json:"owner_id"`
	RepoUrl      pgtype.Text    `json:"repo_url"`
	GitProvider  string         `json:"git_provider"`
	GitTokenEnv  pgtype.Text    `json:"git_token_env"`
	AgentRuntime string         `json:"agent_runtime"`
	DefaultModel pgtype.Text    `json:"default_model"`
	MaxBudget    pgtype.Numeric `json:"max_budget"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ProjectUser struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
