// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_configs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteNotificationConfig = `-- name: DeleteNotificationConfig :exec
DELETE FROM notification_configs WHERE id = $1
`

func (q *Queries) DeleteNotificationConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationConfig, id)
	return err
}

const getNotificationConfig = `-- name: GetNotificationConfig :one
SELECT id, project_id, channel_type, config, events_filter, enabled, created_at, updated_at FROM notification_configs WHERE id = $1
`

func (q *Queries) GetNotificationConfig(ctx context.Context, id uuid.UUID) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, getNotificationConfig, id)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelType,
		&i.Config,
		&i.EventsFilter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationConfig = `-- name: InsertNotificationConfig :one
INSERT INTO notification_configs (project_id, channel_type, config, events_filter, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, channel_type, config, events_filter, enabled, created_at, updated_at
`

type InsertNotificationConfigParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	ChannelType  string    `json:"channel_type"`
	Config       []byte    `json:"config"`
	EventsFilter []byte    `json:"events_filter"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) InsertNotificationConfig(ctx context.Context, arg InsertNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, insertNotificationConfig,
		arg.ProjectID,
		arg.ChannelType,
		arg.Config,
		arg.EventsFilter,
		arg.Enabled,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelType,
		&i.Config,
		&i.EventsFilter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledConfigsByProject = `-- name: ListEnabledConfigsByProject :many
SELECT id, project_id, channel_type, config, events_filter, enabled, created_at, updated_at FROM notification_configs WHERE project_id = $1 AND enabled = true ORDER BY created_at DESC
`

func (q *Queries) ListEnabledConfigsByProject(ctx context.Context, projectID uuid.UUID) ([]NotificationConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledConfigsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationConfig{}
	for rows.Next() {
		var i NotificationConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChannelType,
			&i.Config,
			&i.EventsFilter,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationConfigsByProject = `-- name: ListNotificationConfigsByProject :many
SELECT id, project_id, channel_type, config, events_filter, enabled, created_at, updated_at FROM notification_configs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotificationConfigsByProject(ctx context.Context, projectID uuid.UUID) ([]NotificationConfig, error) {
	rows, err := q.db.Query(ctx, listNotificationConfigsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationConfig{}
	for rows.Next() {
		var i NotificationConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChannelType,
			&i.Config,
			&i.EventsFilter,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationConfig = `-- name: UpdateNotificationConfig :one
UPDATE notification_configs
SET channel_type  = $2,
    config        = $3,
    events_filter = $4,
    enabled       = $5,
    updated_at    = now()
WHERE id = $1
RETURNING id, project_id, channel_type, config, events_filter, enabled, created_at, updated_at
`

type UpdateNotificationConfigParams struct {
	ID           uuid.UUID `json:"id"`
	ChannelType  string    `json:"channel_type"`
	Config       []byte    `json:"config"`
	EventsFilter []byte    `json:"events_filter"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) UpdateNotificationConfig(ctx context.Context, arg UpdateNotificationConfigParams) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, updateNotificationConfig,
		arg.ID,
		arg.ChannelType,
		arg.Config,
		arg.EventsFilter,
		arg.Enabled,
	)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelType,
		&i.Config,
		&i.EventsFilter,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
