// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_configs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getPipelineConfig = `-- name: GetPipelineConfig :one
SELECT id, project_id, config_yaml, version, created_at, updated_at FROM pipeline_configs WHERE project_id = $1
`

func (q *Queries) GetPipelineConfig(ctx context.Context, projectID uuid.UUID) (PipelineConfig, error) {
	row := q.db.QueryRow(ctx, getPipelineConfig, projectID)
	var i PipelineConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConfigYaml,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPipelineConfig = `-- name: UpsertPipelineConfig :one
INSERT INTO pipeline_configs (project_id, config_yaml, version)
VALUES ($1, $2, 1)
ON CONFLICT (project_id) DO UPDATE
SET config_yaml = EXCLUDED.config_yaml,
    version = pipeline_configs.version + 1,
    updated_at = now()
RETURNING id, project_id, config_yaml, version, created_at, updated_at
`

type UpsertPipelineConfigParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	ConfigYaml string    `json:"config_yaml"`
}

func (q *Queries) UpsertPipelineConfig(ctx context.Context, arg UpsertPipelineConfigParams) (PipelineConfig, error) {
	row := q.db.QueryRow(ctx, upsertPipelineConfig, arg.ProjectID, arg.ConfigYaml)
	var i PipelineConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ConfigYaml,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
