// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning_connectors.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanningConnector = `-- name: GetPlanningConnector :one
SELECT project_id, source, project_url, status_field, done_options, epic_issue_type, status_mapping, writeback_enabled, post_run_comment, created_at, updated_at FROM planning_connectors WHERE project_id = $1
`

func (q *Queries) GetPlanningConnector(ctx context.Context, projectID uuid.UUID) (PlanningConnector, error) {
	row := q.db.QueryRow(ctx, getPlanningConnector, projectID)
	var i PlanningConnector
	err := row.Scan(
		&i.ProjectID,
		&i.Source,
		&i.ProjectUrl,
		&i.StatusField,
		&i.DoneOptions,
		&i.EpicIssueType,
		&i.StatusMapping,
		&i.WritebackEnabled,
		&i.PostRunComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlanningConnector = `-- name: UpsertPlanningConnector :one
INSERT INTO planning_connectors (
    project_id, source, project_url, status_field, done_options,
    epic_issue_type, status_mapping, writeback_enabled, post_run_comment
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
ON CONFLICT (project_id) DO UPDATE SET
    source            = $2,
    project_url       = $3,
    status_field      = $4,
    done_options      = $5,
    epic_issue_type   = $6,
    status_mapping    = $7,
    writeback_enabled = $8,
    post_run_comment  = $9,
    updated_at        = now()
RETURNING project_id, source, project_url, status_field, done_options, epic_issue_type, status_mapping, writeback_enabled, post_run_comment, created_at, updated_at
`

type UpsertPlanningConnectorParams struct {
	ProjectID        uuid.UUID   `json:"project_id"`
	Source           string      `json:"source"`
	ProjectUrl       pgtype.Text `json:"project_url"`
	StatusField      string      `json:"status_field"`
	DoneOptions      []byte      `json:"done_options"`
	EpicIssueType    string      `json:"epic_issue_type"`
	StatusMapping    []byte      `json:"status_mapping"`
	WritebackEnabled bool        `json:"writeback_enabled"`
	PostRunComment   bool        `json:"post_run_comment"`
}

func (q *Queries) UpsertPlanningConnector(ctx context.Context, arg UpsertPlanningConnectorParams) (PlanningConnector, error) {
	row := q.db.QueryRow(ctx, upsertPlanningConnector,
		arg.ProjectID,
		arg.Source,
		arg.ProjectUrl,
		arg.StatusField,
		arg.DoneOptions,
		arg.EpicIssueType,
		arg.StatusMapping,
		arg.WritebackEnabled,
		arg.PostRunComment,
	)
	var i PlanningConnector
	err := row.Scan(
		&i.ProjectID,
		&i.Source,
		&i.ProjectUrl,
		&i.StatusField,
		&i.DoneOptions,
		&i.EpicIssueType,
		&i.StatusMapping,
		&i.WritebackEnabled,
		&i.PostRunComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
