// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planning_write_backs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanningWriteBack = `-- name: CreatePlanningWriteBack :one
INSERT INTO planning_write_backs (
    project_id, story_id, run_id, source, external_id,
    internal_status, remote_status, success, error_code, error_message
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, project_id, story_id, run_id, source, external_id, internal_status, remote_status, success, error_code, error_message, created_at
`

type CreatePlanningWriteBackParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	StoryID        uuid.UUID   `json:"story_id"`
	RunID          pgtype.UUID `json:"run_id"`
	Source         pgtype.Text `json:"source"`
	ExternalID     pgtype.Text `json:"external_id"`
	InternalStatus pgtype.Text `json:"internal_status"`
	RemoteStatus   pgtype.Text `json:"remote_status"`
	Success        bool        `json:"success"`
	ErrorCode      pgtype.Text `json:"error_code"`
	ErrorMessage   pgtype.Text `json:"error_message"`
}

// Append-only audit row for one write-back attempt (success or failure).
func (q *Queries) CreatePlanningWriteBack(ctx context.Context, arg CreatePlanningWriteBackParams) (PlanningWriteBack, error) {
	row := q.db.QueryRow(ctx, createPlanningWriteBack,
		arg.ProjectID,
		arg.StoryID,
		arg.RunID,
		arg.Source,
		arg.ExternalID,
		arg.InternalStatus,
		arg.RemoteStatus,
		arg.Success,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i PlanningWriteBack
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.RunID,
		&i.Source,
		&i.ExternalID,
		&i.InternalStatus,
		&i.RemoteStatus,
		&i.Success,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanningWriteBacksByStory = `-- name: ListPlanningWriteBacksByStory :many
SELECT id, project_id, story_id, run_id, source, external_id, internal_status, remote_status, success, error_code, error_message, created_at FROM planning_write_backs
WHERE story_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPlanningWriteBacksByStoryParams struct {
	StoryID uuid.UUID `json:"story_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListPlanningWriteBacksByStory(ctx context.Context, arg ListPlanningWriteBacksByStoryParams) ([]PlanningWriteBack, error) {
	rows, err := q.db.Query(ctx, listPlanningWriteBacksByStory, arg.StoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanningWriteBack{}
	for rows.Next() {
		var i PlanningWriteBack
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.RunID,
			&i.Source,
			&i.ExternalID,
			&i.InternalStatus,
			&i.RemoteStatus,
			&i.Success,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
