// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max
`

type CreateProjectParams struct {
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	OwnerID      pgtype.UUID    `json:"owner_id"`
	RepoUrl      pgtype.Text    `json:"repo_url"`
	GitProvider  string         `json:"git_provider"`
	GitTokenEnv  pgtype.Text    `json:"git_token_env"`
	AgentRuntime string         `json:"agent_runtime"`
	DefaultModel pgtype.Text    `json:"default_model"`
	MaxBudget    pgtype.Numeric `json:"max_budget"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.RepoUrl,
		arg.GitProvider,
		arg.GitTokenEnv,
		arg.AgentRuntime,
		arg.DefaultModel,
		arg.MaxBudget,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.RepoUrl,
		&i.GitProvider,
		&i.GitTokenEnv,
		&i.AgentRuntime,
		&i.DefaultModel,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getCircuitBreakerState = `-- name: GetCircuitBreakerState :one
SELECT id, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max
FROM projects
WHERE id = $1
`

type GetCircuitBreakerStateRow struct {
	ID                   uuid.UUID `json:"id"`
	CircuitBreakerCount  int32     `json:"circuit_breaker_count"`
	CircuitBreakerActive bool      `json:"circuit_breaker_active"`
	CircuitBreakerMax    int32     `json:"circuit_breaker_max"`
}

func (q *Queries) GetCircuitBreakerState(ctx context.Context, id uuid.UUID) (GetCircuitBreakerStateRow, error) {
	row := q.db.QueryRow(ctx, getCircuitBreakerState, id)
	var i GetCircuitBreakerStateRow
	err := row.Scan(
		&i.ID,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.RepoUrl,
		&i.GitProvider,
		&i.GitTokenEnv,
		&i.AgentRuntime,
		&i.DefaultModel,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}

const incrementCircuitBreakerCount = `-- name: IncrementCircuitBreakerCount :one
UPDATE projects
SET circuit_breaker_count = circuit_breaker_count + 1,
    circuit_breaker_active = CASE
        WHEN circuit_breaker_count + 1 >= circuit_breaker_max THEN true
        ELSE circuit_breaker_active
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max
`

func (q *Queries) IncrementCircuitBreakerCount(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, incrementCircuitBreakerCount, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.RepoUrl,
		&i.GitProvider,
		&i.GitTokenEnv,
		&i.AgentRuntime,
		&i.DefaultModel,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max FROM projects ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.RepoUrl,
			&i.GitProvider,
			&i.GitTokenEnv,
			&i.AgentRuntime,
			&i.DefaultModel,
			&i.MaxBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CircuitBreakerCount,
			&i.CircuitBreakerActive,
			&i.CircuitBreakerMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCircuitBreaker = `-- name: ResetCircuitBreaker :one
UPDATE projects
SET circuit_breaker_count = 0,
    circuit_breaker_active = false,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max
`

func (q *Queries) ResetCircuitBreaker(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, resetCircuitBreaker, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.RepoUrl,
		&i.GitProvider,
		&i.GitTokenEnv,
		&i.AgentRuntime,
		&i.DefaultModel,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    owner_id = COALESCE($3, owner_id),
    repo_url = COALESCE($4, repo_url),
    git_provider = COALESCE($5, git_provider),
    git_token_env = COALESCE($6, git_token_env),
    agent_runtime = COALESCE($7, agent_runtime),
    default_model = COALESCE($8, default_model),
    max_budget = COALESCE($9, max_budget),
    updated_at = now()
WHERE id = $10
RETURNING id, name, description, owner_id, repo_url, git_provider, git_token_env, agent_runtime, default_model, max_budget, created_at, updated_at, circuit_breaker_count, circuit_breaker_active, circuit_breaker_max
`

type UpdateProjectParams struct {
	Name         pgtype.Text    `json:"name"`
	Description  pgtype.Text    `json:"description"`
	OwnerID      pgtype.UUID    `json:"owner_id"`
	RepoUrl      pgtype.Text    `json:"repo_url"`
	GitProvider  pgtype.Text    `json:"git_provider"`
	GitTokenEnv  pgtype.Text    `json:"git_token_env"`
	AgentRuntime pgtype.Text    `json:"agent_runtime"`
	DefaultModel pgtype.Text    `json:"default_model"`
	MaxBudget    pgtype.Numeric `json:"max_budget"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.RepoUrl,
		arg.GitProvider,
		arg.GitTokenEnv,
		arg.AgentRuntime,
		arg.DefaultModel,
		arg.MaxBudget,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.RepoUrl,
		&i.GitProvider,
		&i.GitTokenEnv,
		&i.AgentRuntime,
		&i.DefaultModel,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CircuitBreakerCount,
		&i.CircuitBreakerActive,
		&i.CircuitBreakerMax,
	)
	return i, err
}
