// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_users.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserToProject = `-- name: AddUserToProject :one
INSERT INTO project_users (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, role, created_at
`

type AddUserToProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddUserToProject(ctx context.Context, arg AddUserToProjectParams) (ProjectUser, error) {
	row := q.db.QueryRow(ctx, addUserToProject, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectUser
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*) FROM projects p
INNER JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isUserInProject = `-- name: IsUserInProject :one
SELECT EXISTS(
    SELECT 1 FROM project_users WHERE project_id = $1 AND user_id = $2
) AS is_member
`

type IsUserInProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsUserInProject(ctx context.Context, arg IsUserInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInProject, arg.ProjectID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listProjectUsers = `-- name: ListProjectUsers :many
SELECT u.id, u.email, u.name, u.role AS user_role, pu.role AS project_role, pu.created_at AS assigned_at
FROM project_users pu
JOIN users u ON u.id = pu.user_id
WHERE pu.project_id = $1
ORDER BY pu.created_at ASC
`

type ListProjectUsersRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	UserRole    string    `json:"user_role"`
	ProjectRole string    `json:"project_role"`
	AssignedAt  time.Time `json:"assigned_at"`
}

func (q *Queries) ListProjectUsers(ctx context.Context, projectID uuid.UUID) ([]ListProjectUsersRow, error) {
	rows, err := q.db.Query(ctx, listProjectUsers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectUsersRow{}
	for rows.Next() {
		var i ListProjectUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.UserRole,
			&i.ProjectRole,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.name, p.description, p.owner_id, p.repo_url, p.git_provider, p.git_token_env, p.agent_runtime, p.default_model, p.max_budget, p.created_at, p.updated_at, p.circuit_breaker_count, p.circuit_breaker_active, p.circuit_breaker_max FROM projects p
INNER JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.RepoUrl,
			&i.GitProvider,
			&i.GitTokenEnv,
			&i.AgentRuntime,
			&i.DefaultModel,
			&i.MaxBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CircuitBreakerCount,
			&i.CircuitBreakerActive,
			&i.CircuitBreakerMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectIDs = `-- name: ListUserProjectIDs :many
SELECT project_id FROM project_users WHERE user_id = $1
`

func (q *Queries) ListUserProjectIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var project_id uuid.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromProject = `-- name: RemoveUserFromProject :exec
DELETE FROM project_users WHERE project_id = $1 AND user_id = $2
`

type RemoveUserFromProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveUserFromProject(ctx context.Context, arg RemoveUserFromProjectParams) error {
	_, err := q.db.Exec(ctx, removeUserFromProject, arg.ProjectID, arg.UserID)
	return err
}
