// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_templates.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPromptTemplatesByProject = `-- name: CountPromptTemplatesByProject :one
SELECT COUNT(*) FROM prompt_templates WHERE project_id = $1
`

func (q *Queries) CountPromptTemplatesByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPromptTemplatesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO prompt_templates (project_id, name, template_content, type)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, template_content, type, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	Name            string    `json:"name"`
	TemplateContent string    `json:"template_content"`
	Type            string    `json:"type"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, createPromptTemplate,
		arg.ProjectID,
		arg.Name,
		arg.TemplateContent,
		arg.Type,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :exec
DELETE FROM prompt_templates WHERE id = $1
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePromptTemplate, id)
	return err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, project_id, name, template_content, type, created_at, updated_at FROM prompt_templates WHERE id = $1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByProjectAndName = `-- name: GetPromptTemplateByProjectAndName :one
SELECT id, project_id, name, template_content, type, created_at, updated_at FROM prompt_templates
WHERE project_id = $1 AND name = $2
`

type GetPromptTemplateByProjectAndNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetPromptTemplateByProjectAndName(ctx context.Context, arg GetPromptTemplateByProjectAndNameParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, getPromptTemplateByProjectAndName, arg.ProjectID, arg.Name)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptTemplatesByProject = `-- name: ListPromptTemplatesByProject :many
SELECT id, project_id, name, template_content, type, created_at, updated_at FROM prompt_templates
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPromptTemplatesByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListPromptTemplatesByProject(ctx context.Context, arg ListPromptTemplatesByProjectParams) ([]PromptTemplate, error) {
	rows, err := q.db.Query(ctx, listPromptTemplatesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptTemplate{}
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TemplateContent,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptTemplate = `-- name: UpdatePromptTemplate :one
UPDATE prompt_templates
SET name = COALESCE($1, name),
    template_content = COALESCE($2, template_content),
    type = COALESCE($3, type),
    updated_at = now()
WHERE id = $4
RETURNING id, project_id, name, template_content, type, created_at, updated_at
`

type UpdatePromptTemplateParams struct {
	Name            pgtype.Text `json:"name"`
	TemplateContent pgtype.Text `json:"template_content"`
	Type            pgtype.Text `json:"type"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, updatePromptTemplate,
		arg.Name,
		arg.TemplateContent,
		arg.Type,
		arg.ID,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TemplateContent,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
