// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoked_tokens.sql

package postgres

import (
	"context"
	"time"
)

const deleteExpiredRevokedTokens = `-- name: DeleteExpiredRevokedTokens :exec
DELETE FROM revoked_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRevokedTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRevokedTokens)
	return err
}

const insertRevokedToken = `-- name: InsertRevokedToken :exec
INSERT INTO revoked_tokens (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT (jti) DO NOTHING
`

type InsertRevokedTokenParams struct {
	Jti       string    `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertRevokedToken(ctx context.Context, arg InsertRevokedTokenParams) error {
	_, err := q.db.Exec(ctx, insertRevokedToken, arg.Jti, arg.ExpiresAt)
	return err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoked_tokens WHERE jti = $1
) AS revoked
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}
