// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRunsByProject = `-- name: CountRunsByProject :one
SELECT COUNT(*) FROM runs WHERE project_id = $1
`

func (q *Queries) CountRunsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunsByStory = `-- name: CountRunsByStory :one
SELECT COUNT(*) FROM runs WHERE story_id = $1
`

func (q *Queries) CountRunsByStory(ctx context.Context, storyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByStory, storyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, story_id, status, pipeline_config_snapshot, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata
`

type CreateRunParams struct {
	ProjectID              uuid.UUID `json:"project_id"`
	StoryID                uuid.UUID `json:"story_id"`
	Status                 string    `json:"status"`
	PipelineConfigSnapshot []byte    `json:"pipeline_config_snapshot"`
	Metadata               []byte    `json:"metadata"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.StoryID,
		arg.Status,
		arg.PipelineConfigSnapshot,
		arg.Metadata,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.Metadata,
	)
	return i, err
}

const getActiveRunByStory = `-- name: GetActiveRunByStory :one
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata FROM runs
WHERE story_id = $1 AND status IN ('pending', 'running', 'paused')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRunByStory(ctx context.Context, storyID uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getActiveRunByStory, storyID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.Metadata,
	)
	return i, err
}

const getDAGNodeRunInfoByStories = `-- name: GetDAGNodeRunInfoByStories :many
SELECT DISTINCT ON (r.story_id)
    r.story_id              AS story_id,
    r.id                   AS run_id,
    r.status               AS run_status,
    (
        SELECT s.container_id
        FROM run_steps s
        WHERE s.run_id = r.id AND s.container_id IS NOT NULL
        ORDER BY (s.status IN ('running', 'waiting_approval')) DESC, s.step_order DESC
        LIMIT 1
    )                      AS container_id,
    (
        SELECT COALESCE(SUM(cr.cost_usd), 0)::DECIMAL(10,6)
        FROM cost_records cr
        JOIN run_steps rs ON rs.id = cr.run_step_id
        WHERE rs.run_id = r.id
    )                      AS cost_usd
FROM runs r
WHERE r.story_id = ANY($1::uuid[])
ORDER BY r.story_id, r.created_at DESC
`

type GetDAGNodeRunInfoByStoriesRow struct {
	StoryID     uuid.UUID      `json:"story_id"`
	RunID       uuid.UUID      `json:"run_id"`
	RunStatus   string         `json:"run_status"`
	ContainerID pgtype.Text    `json:"container_id"`
	CostUsd     pgtype.Numeric `json:"cost_usd"`
}

// Per-story enrichment for the epic DAG: the latest run id/status, the most
// relevant container id of that run (the active step's container, else the most
// recent step that has one), and the total cost incurred by that latest run.
// One row per story that has at least one run; stories with no run are absent.
// No status filter on cost so a failed run reports its real total.
func (q *Queries) GetDAGNodeRunInfoByStories(ctx context.Context, dollar_1 []uuid.UUID) ([]GetDAGNodeRunInfoByStoriesRow, error) {
	rows, err := q.db.Query(ctx, getDAGNodeRunInfoByStories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDAGNodeRunInfoByStoriesRow{}
	for rows.Next() {
		var i GetDAGNodeRunInfoByStoriesRow
		if err := rows.Scan(
			&i.StoryID,
			&i.RunID,
			&i.RunStatus,
			&i.ContainerID,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestRunByStory = `-- name: GetLatestRunByStory :one
SELECT
    r.id AS run_id,
    r.status AS run_status,
    (
        SELECT to_jsonb(cs)
        FROM (
            SELECT s.id, s.step_name AS name, s.action AS action_type, s.status, s.step_order AS index, s.container_id
            FROM run_steps s
            WHERE s.run_id = r.id AND s.status IN ('running', 'waiting_approval')
            ORDER BY s.step_order ASC
            LIMIT 1
        ) cs
    ) AS current_step,
    (SELECT COUNT(*) FROM run_steps s WHERE s.run_id = r.id)::int AS total_steps
FROM runs r
WHERE r.story_id = $1
ORDER BY r.created_at DESC
LIMIT 1
`

type GetLatestRunByStoryRow struct {
	RunID       uuid.UUID `json:"run_id"`
	RunStatus   string    `json:"run_status"`
	CurrentStep []byte    `json:"current_step"`
	TotalSteps  int32     `json:"total_steps"`
}

// Returns the most recent run for a story along with its current in-progress step
// (running or waiting_approval, lowest step_order) and the total step count.
// current_step is a JSON object (NULL when no step is in progress) carrying
// id, name, action_type, status, index (step_order) and container_id.
func (q *Queries) GetLatestRunByStory(ctx context.Context, storyID uuid.UUID) (GetLatestRunByStoryRow, error) {
	row := q.db.QueryRow(ctx, getLatestRunByStory, storyID)
	var i GetLatestRunByStoryRow
	err := row.Scan(
		&i.RunID,
		&i.RunStatus,
		&i.CurrentStep,
		&i.TotalSteps,
	)
	return i, err
}

const getLatestRunsByStories = `-- name: GetLatestRunsByStories :many
SELECT DISTINCT ON (r.story_id)
    r.story_id AS story_id,
    r.id AS run_id,
    r.status AS run_status,
    (
        SELECT to_jsonb(cs)
        FROM (
            SELECT s.id, s.step_name AS name, s.action AS action_type, s.status, s.step_order AS index, s.container_id
            FROM run_steps s
            WHERE s.run_id = r.id AND s.status IN ('running', 'waiting_approval')
            ORDER BY s.step_order ASC
            LIMIT 1
        ) cs
    ) AS current_step,
    (SELECT COUNT(*) FROM run_steps s WHERE s.run_id = r.id)::int AS total_steps
FROM runs r
WHERE r.story_id = ANY($1::uuid[])
ORDER BY r.story_id, r.created_at DESC
`

type GetLatestRunsByStoriesRow struct {
	StoryID     uuid.UUID `json:"story_id"`
	RunID       uuid.UUID `json:"run_id"`
	RunStatus   string    `json:"run_status"`
	CurrentStep []byte    `json:"current_step"`
	TotalSteps  int32     `json:"total_steps"`
}

// Batch version of GetLatestRunByStory: returns the most recent run per story
// for the given story IDs, with current step (JSON) and total step count.
// Avoids N+1 when listing stories of an epic.
func (q *Queries) GetLatestRunsByStories(ctx context.Context, dollar_1 []uuid.UUID) ([]GetLatestRunsByStoriesRow, error) {
	rows, err := q.db.Query(ctx, getLatestRunsByStories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestRunsByStoriesRow{}
	for rows.Next() {
		var i GetLatestRunsByStoriesRow
		if err := rows.Scan(
			&i.StoryID,
			&i.RunID,
			&i.RunStatus,
			&i.CurrentStep,
			&i.TotalSteps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.Metadata,
	)
	return i, err
}

const getRunWithStoryKey = `-- name: GetRunWithStoryKey :one
SELECT r.id, r.project_id, r.story_id, r.status, r.pipeline_config_snapshot,
       r.started_at, r.completed_at, r.error_message, r.created_at, r.updated_at,
       r.paused_at, r.metadata, COALESCE(s.key, '') AS story_key
FROM runs r
LEFT JOIN stories s ON s.id = r.story_id
WHERE r.id = $1
`

type GetRunWithStoryKeyRow struct {
	ID                     uuid.UUID          `json:"id"`
	ProjectID              uuid.UUID          `json:"project_id"`
	StoryID                uuid.UUID          `json:"story_id"`
	Status                 string             `json:"status"`
	PipelineConfigSnapshot []byte             `json:"pipeline_config_snapshot"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage           pgtype.Text        `json:"error_message"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	Metadata               []byte             `json:"metadata"`
	StoryKey               string             `json:"story_key"`
}

func (q *Queries) GetRunWithStoryKey(ctx context.Context, id uuid.UUID) (GetRunWithStoryKeyRow, error) {
	row := q.db.QueryRow(ctx, getRunWithStoryKey, id)
	var i GetRunWithStoryKeyRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.Metadata,
		&i.StoryKey,
	)
	return i, err
}

const listChildRunsByParent = `-- name: ListChildRunsByParent :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata FROM runs
WHERE project_id = $1 AND pipeline_config_snapshot @> $2::jsonb
ORDER BY created_at ASC
`

type ListChildRunsByParentParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	ParentFilter []byte    `json:"parent_filter"`
}

func (q *Queries) ListChildRunsByParent(ctx context.Context, arg ListChildRunsByParentParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listChildRunsByParent, arg.ProjectID, arg.ParentFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata FROM runs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProjectWithStoryKey = `-- name: ListRunsByProjectWithStoryKey :many
SELECT r.id, r.project_id, r.story_id, r.status, r.pipeline_config_snapshot,
       r.started_at, r.completed_at, r.error_message, r.created_at, r.updated_at,
       r.paused_at, r.metadata, COALESCE(s.key, '') AS story_key
FROM runs r
LEFT JOIN stories s ON s.id = r.story_id
WHERE r.project_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByProjectWithStoryKeyParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListRunsByProjectWithStoryKeyRow struct {
	ID                     uuid.UUID          `json:"id"`
	ProjectID              uuid.UUID          `json:"project_id"`
	StoryID                uuid.UUID          `json:"story_id"`
	Status                 string             `json:"status"`
	PipelineConfigSnapshot []byte             `json:"pipeline_config_snapshot"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage           pgtype.Text        `json:"error_message"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	Metadata               []byte             `json:"metadata"`
	StoryKey               string             `json:"story_key"`
}

func (q *Queries) ListRunsByProjectWithStoryKey(ctx context.Context, arg ListRunsByProjectWithStoryKeyParams) ([]ListRunsByProjectWithStoryKeyRow, error) {
	rows, err := q.db.Query(ctx, listRunsByProjectWithStoryKey, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsByProjectWithStoryKeyRow{}
	for rows.Next() {
		var i ListRunsByProjectWithStoryKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.Metadata,
			&i.StoryKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStory = `-- name: ListRunsByStory :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata FROM runs
WHERE story_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByStoryParams struct {
	StoryID uuid.UUID `json:"story_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListRunsByStory(ctx context.Context, arg ListRunsByStoryParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByStory, arg.StoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2,
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at),
    paused_at = COALESCE($5, paused_at),
    error_message = COALESCE($6, error_message),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at, metadata
`

type UpdateRunStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	PausedAt     pgtype.Timestamptz `json:"paused_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.PausedAt,
		arg.ErrorMessage,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
		&i.Metadata,
	)
	return i, err
}
