// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRunsByProject = `-- name: CountRunsByProject :one
SELECT COUNT(*) FROM runs WHERE project_id = $1
`

func (q *Queries) CountRunsByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunsByStory = `-- name: CountRunsByStory :one
SELECT COUNT(*) FROM runs WHERE story_id = $1
`

func (q *Queries) CountRunsByStory(ctx context.Context, storyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByStory, storyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, story_id, status, pipeline_config_snapshot)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at
`

type CreateRunParams struct {
	ProjectID              uuid.UUID `json:"project_id"`
	StoryID                uuid.UUID `json:"story_id"`
	Status                 string    `json:"status"`
	PipelineConfigSnapshot []byte    `json:"pipeline_config_snapshot"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ProjectID,
		arg.StoryID,
		arg.Status,
		arg.PipelineConfigSnapshot,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const getActiveRunByStory = `-- name: GetActiveRunByStory :one
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at FROM runs
WHERE story_id = $1 AND status IN ('pending', 'running', 'paused')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRunByStory(ctx context.Context, storyID uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getActiveRunByStory, storyID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const listChildRunsByParent = `-- name: ListChildRunsByParent :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at FROM runs
WHERE project_id = $1 AND pipeline_config_snapshot @> $2::jsonb
ORDER BY created_at ASC
`

type ListChildRunsByParentParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	ParentFilter []byte    `json:"parent_filter"`
}

func (q *Queries) ListChildRunsByParent(ctx context.Context, arg ListChildRunsByParentParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listChildRunsByParent, arg.ProjectID, arg.ParentFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at FROM runs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListRunsByProject(ctx context.Context, arg ListRunsByProjectParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStory = `-- name: ListRunsByStory :many
SELECT id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at FROM runs
WHERE story_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByStoryParams struct {
	StoryID uuid.UUID `json:"story_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListRunsByStory(ctx context.Context, arg ListRunsByStoryParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByStory, arg.StoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StoryID,
			&i.Status,
			&i.PipelineConfigSnapshot,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2,
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at),
    paused_at = COALESCE($5, paused_at),
    error_message = COALESCE($6, error_message),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, story_id, status, pipeline_config_snapshot, started_at, completed_at, error_message, created_at, updated_at, paused_at
`

type UpdateRunStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	PausedAt     pgtype.Timestamptz `json:"paused_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.PausedAt,
		arg.ErrorMessage,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StoryID,
		&i.Status,
		&i.PipelineConfigSnapshot,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}
