// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stacks.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getStack = `-- name: GetStack :one
SELECT id, key, image_ref, toolchain, created_at FROM stacks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStack(ctx context.Context, id uuid.UUID) (Stack, error) {
	row := q.db.QueryRow(ctx, getStack, id)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ImageRef,
		&i.Toolchain,
		&i.CreatedAt,
	)
	return i, err
}

const getStackByKey = `-- name: GetStackByKey :one
SELECT id, key, image_ref, toolchain, created_at FROM stacks WHERE key = $1 LIMIT 1
`

func (q *Queries) GetStackByKey(ctx context.Context, key string) (Stack, error) {
	row := q.db.QueryRow(ctx, getStackByKey, key)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ImageRef,
		&i.Toolchain,
		&i.CreatedAt,
	)
	return i, err
}

const listStacks = `-- name: ListStacks :many
SELECT id, key, image_ref, toolchain, created_at FROM stacks ORDER BY key ASC
`

func (q *Queries) ListStacks(ctx context.Context) ([]Stack, error) {
	rows, err := q.db.Query(ctx, listStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stack{}
	for rows.Next() {
		var i Stack
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ImageRef,
			&i.Toolchain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
