// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStoriesByEpicGroupedByStatus = `-- name: CountStoriesByEpicGroupedByStatus :many
SELECT status, COUNT(*) AS count
FROM stories
WHERE epic_id = $1
GROUP BY status
`

type CountStoriesByEpicGroupedByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountStoriesByEpicGroupedByStatus(ctx context.Context, epicID pgtype.UUID) ([]CountStoriesByEpicGroupedByStatusRow, error) {
	rows, err := q.db.Query(ctx, countStoriesByEpicGroupedByStatus, epicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountStoriesByEpicGroupedByStatusRow{}
	for rows.Next() {
		var i CountStoriesByEpicGroupedByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStoriesByProject = `-- name: CountStoriesByProject :one
SELECT COUNT(*) FROM stories WHERE project_id = $1
`

func (q *Queries) CountStoriesByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoriesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoriesByStatus = `-- name: CountStoriesByStatus :one
SELECT COUNT(*) FROM stories WHERE project_id = $1 AND status = ANY($2::text[])
`

type CountStoriesByStatusParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   []string  `json:"column_2"`
}

func (q *Queries) CountStoriesByStatus(ctx context.Context, arg CountStoriesByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStoriesByStatus, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash
`

type CreateStoryParams struct {
	ProjectID          uuid.UUID   `json:"project_id"`
	EpicID             pgtype.UUID `json:"epic_id"`
	Key                string      `json:"key"`
	Title              string      `json:"title"`
	Objective          pgtype.Text `json:"objective"`
	TargetFiles        []byte      `json:"target_files"`
	DependsOn          []byte      `json:"depends_on"`
	Scope              pgtype.Text `json:"scope"`
	Status             string      `json:"status"`
	AcceptanceCriteria pgtype.Text `json:"acceptance_criteria"`
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.ProjectID,
		arg.EpicID,
		arg.Key,
		arg.Title,
		arg.Objective,
		arg.TargetFiles,
		arg.DependsOn,
		arg.Scope,
		arg.Status,
		arg.AcceptanceCriteria,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Key,
		&i.Title,
		&i.Objective,
		&i.TargetFiles,
		&i.DependsOn,
		&i.Scope,
		&i.Status,
		&i.AcceptanceCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.SyncedAt,
		&i.LastImportHash,
	)
	return i, err
}

const deleteStory = `-- name: DeleteStory :exec
DELETE FROM stories WHERE id = $1
`

func (q *Queries) DeleteStory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStory, id)
	return err
}

const getStory = `-- name: GetStory :one
SELECT id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash FROM stories WHERE id = $1
`

func (q *Queries) GetStory(ctx context.Context, id uuid.UUID) (Story, error) {
	row := q.db.QueryRow(ctx, getStory, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Key,
		&i.Title,
		&i.Objective,
		&i.TargetFiles,
		&i.DependsOn,
		&i.Scope,
		&i.Status,
		&i.AcceptanceCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.SyncedAt,
		&i.LastImportHash,
	)
	return i, err
}

const getStoryByKey = `-- name: GetStoryByKey :one
SELECT id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash FROM stories WHERE project_id = $1 AND key = $2
`

type GetStoryByKeyParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetStoryByKey(ctx context.Context, arg GetStoryByKeyParams) (Story, error) {
	row := q.db.QueryRow(ctx, getStoryByKey, arg.ProjectID, arg.Key)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Key,
		&i.Title,
		&i.Objective,
		&i.TargetFiles,
		&i.DependsOn,
		&i.Scope,
		&i.Status,
		&i.AcceptanceCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.SyncedAt,
		&i.LastImportHash,
	)
	return i, err
}

const listStoriesByEpic = `-- name: ListStoriesByEpic :many
SELECT id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash FROM stories
WHERE epic_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStoriesByEpicParams struct {
	EpicID pgtype.UUID `json:"epic_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListStoriesByEpic(ctx context.Context, arg ListStoriesByEpicParams) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStoriesByEpic, arg.EpicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpicID,
			&i.Key,
			&i.Title,
			&i.Objective,
			&i.TargetFiles,
			&i.DependsOn,
			&i.Scope,
			&i.Status,
			&i.AcceptanceCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.SyncedAt,
			&i.LastImportHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoriesByProject = `-- name: ListStoriesByProject :many
SELECT id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash FROM stories
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListStoriesByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListStoriesByProject(ctx context.Context, arg ListStoriesByProjectParams) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStoriesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpicID,
			&i.Key,
			&i.Title,
			&i.Objective,
			&i.TargetFiles,
			&i.DependsOn,
			&i.Scope,
			&i.Status,
			&i.AcceptanceCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.SyncedAt,
			&i.LastImportHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoriesByStatus = `-- name: ListStoriesByStatus :many
SELECT id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash FROM stories
WHERE project_id = $1 AND status = ANY($2::text[])
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListStoriesByStatusParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Column2   []string  `json:"column_2"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListStoriesByStatus(ctx context.Context, arg ListStoriesByStatusParams) ([]Story, error) {
	rows, err := q.db.Query(ctx, listStoriesByStatus,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Story{}
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EpicID,
			&i.Key,
			&i.Title,
			&i.Objective,
			&i.TargetFiles,
			&i.DependsOn,
			&i.Scope,
			&i.Status,
			&i.AcceptanceCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentStage,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.SyncedAt,
			&i.LastImportHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStory = `-- name: UpdateStory :one
UPDATE stories
SET title = COALESCE($1, title),
    objective = COALESCE($2, objective),
    target_files = COALESCE($3, target_files),
    depends_on = COALESCE($4, depends_on),
    scope = COALESCE($5, scope),
    status = COALESCE($6, status),
    acceptance_criteria = COALESCE($7, acceptance_criteria),
    epic_id = COALESCE($8, epic_id),
    updated_at = now()
WHERE id = $9
RETURNING id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash
`

type UpdateStoryParams struct {
	Title              pgtype.Text `json:"title"`
	Objective          pgtype.Text `json:"objective"`
	TargetFiles        []byte      `json:"target_files"`
	DependsOn          []byte      `json:"depends_on"`
	Scope              pgtype.Text `json:"scope"`
	Status             pgtype.Text `json:"status"`
	AcceptanceCriteria pgtype.Text `json:"acceptance_criteria"`
	EpicID             pgtype.UUID `json:"epic_id"`
	ID                 uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, updateStory,
		arg.Title,
		arg.Objective,
		arg.TargetFiles,
		arg.DependsOn,
		arg.Scope,
		arg.Status,
		arg.AcceptanceCriteria,
		arg.EpicID,
		arg.ID,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Key,
		&i.Title,
		&i.Objective,
		&i.TargetFiles,
		&i.DependsOn,
		&i.Scope,
		&i.Status,
		&i.AcceptanceCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.SyncedAt,
		&i.LastImportHash,
	)
	return i, err
}

const updateStoryCurrentStage = `-- name: UpdateStoryCurrentStage :one
UPDATE stories
SET current_stage = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, project_id, epic_id, key, title, objective, target_files, depends_on, scope, status, acceptance_criteria, created_at, updated_at, current_stage, source, external_id, source_url, synced_at, last_import_hash
`

type UpdateStoryCurrentStageParams struct {
	CurrentStage pgtype.Text `json:"current_stage"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStoryCurrentStage(ctx context.Context, arg UpdateStoryCurrentStageParams) (Story, error) {
	row := q.db.QueryRow(ctx, updateStoryCurrentStage, arg.CurrentStage, arg.ID)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EpicID,
		&i.Key,
		&i.Title,
		&i.Objective,
		&i.TargetFiles,
		&i.DependsOn,
		&i.Scope,
		&i.Status,
		&i.AcceptanceCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentStage,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.SyncedAt,
		&i.LastImportHash,
	)
	return i, err
}
