// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_api_keys.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createUserAPIKey = `-- name: CreateUserAPIKey :one
INSERT INTO user_api_keys (id, user_id, provider, key_name, encrypted_key, key_hint, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, user_id, provider, key_name, encrypted_key, key_hint, created_at, updated_at
`

type CreateUserAPIKeyParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	KeyName      string    `json:"key_name"`
	EncryptedKey []byte    `json:"encrypted_key"`
	KeyHint      string    `json:"key_hint"`
}

func (q *Queries) CreateUserAPIKey(ctx context.Context, arg CreateUserAPIKeyParams) (UserApiKey, error) {
	row := q.db.QueryRow(ctx, createUserAPIKey,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.KeyName,
		arg.EncryptedKey,
		arg.KeyHint,
	)
	var i UserApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.KeyName,
		&i.EncryptedKey,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserAPIKey = `-- name: DeleteUserAPIKey :exec
DELETE FROM user_api_keys WHERE id = $1
`

func (q *Queries) DeleteUserAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAPIKey, id)
	return err
}

const getUserAPIKey = `-- name: GetUserAPIKey :one
SELECT id, user_id, provider, key_name, encrypted_key, key_hint, created_at, updated_at FROM user_api_keys WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserAPIKey(ctx context.Context, id uuid.UUID) (UserApiKey, error) {
	row := q.db.QueryRow(ctx, getUserAPIKey, id)
	var i UserApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.KeyName,
		&i.EncryptedKey,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAPIKeyByProvider = `-- name: GetUserAPIKeyByProvider :one
SELECT id, user_id, provider, key_name, encrypted_key, key_hint, created_at, updated_at FROM user_api_keys WHERE user_id = $1 AND provider = $2 LIMIT 1
`

type GetUserAPIKeyByProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetUserAPIKeyByProvider(ctx context.Context, arg GetUserAPIKeyByProviderParams) (UserApiKey, error) {
	row := q.db.QueryRow(ctx, getUserAPIKeyByProvider, arg.UserID, arg.Provider)
	var i UserApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.KeyName,
		&i.EncryptedKey,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAPIKeys = `-- name: ListUserAPIKeys :many
SELECT id, user_id, provider, key_name, encrypted_key, key_hint, created_at, updated_at FROM user_api_keys WHERE user_id = $1 ORDER BY provider, key_name ASC
`

func (q *Queries) ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]UserApiKey, error) {
	rows, err := q.db.Query(ctx, listUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserApiKey{}
	for rows.Next() {
		var i UserApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.KeyName,
			&i.EncryptedKey,
			&i.KeyHint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
