// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchdog.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listRunningStepsForWatchdog = `-- name: ListRunningStepsForWatchdog :many
SELECT
    rs.id            AS step_id,
    rs.run_id        AS run_id,
    rs.step_name     AS step_name,
    rs.stage_id      AS stage_id,
    rs.stage_name    AS stage_name,
    rs.started_at    AS started_at,
    r.project_id     AS project_id,
    r.story_id       AS story_id,
    ll.last_log_at   AS last_log_at
FROM run_steps rs
JOIN runs r ON r.id = rs.run_id
LEFT JOIN LATERAL (
    SELECT max(e.created_at) AS last_log_at
    FROM events e
    WHERE e.entity_type = 'log'
      AND e.entity_id = rs.id
      AND e.action = 'emitted'
) ll ON true
WHERE rs.status = 'running'
  AND r.status = 'running'
`

type ListRunningStepsForWatchdogRow struct {
	StepID    uuid.UUID          `json:"step_id"`
	RunID     uuid.UUID          `json:"run_id"`
	StepName  string             `json:"step_name"`
	StageID   pgtype.Text        `json:"stage_id"`
	StageName pgtype.Text        `json:"stage_name"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ProjectID uuid.UUID          `json:"project_id"`
	StoryID   uuid.UUID          `json:"story_id"`
	LastLogAt interface{}        `json:"last_log_at"`
}

// All currently-running run steps across every project, enriched with the run
// context the watchdog needs (project, story) and the timestamp of the most
// recent log.emitted event for the step (NULL when no log yet). The watchdog
// compares now() against last_log_at (log_silence), started_at (wallclock) and
// the run's cumulative cost (cost_batch). Only running steps of running runs are
// returned — a paused run is already halted, skip it. The LEFT JOIN LATERAL
// keeps last_log_at nullable (vs a scalar subquery, which sqlc infers non-null).
func (q *Queries) ListRunningStepsForWatchdog(ctx context.Context) ([]ListRunningStepsForWatchdogRow, error) {
	rows, err := q.db.Query(ctx, listRunningStepsForWatchdog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningStepsForWatchdogRow{}
	for rows.Next() {
		var i ListRunningStepsForWatchdogRow
		if err := rows.Scan(
			&i.StepID,
			&i.RunID,
			&i.StepName,
			&i.StageID,
			&i.StageName,
			&i.StartedAt,
			&i.ProjectID,
			&i.StoryID,
			&i.LastLogAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
